
RESOURCE

TASK TaskMain (PRIORITY := 7);
  PRG_Start_MultiMotion();
  MC_FieldbusHandlerIN( Enable := TRUE );
  MC_MoviPlcHandlerIN( Enable := TRUE );
     PRG_TaskMain();
     PRG_TaskMain_Kinematics();
     AxisHandler_Main_MultiMotion();
     AxisHandler_BasicMotion();
     CamSwitchHandler_Main();
   MC_MoviPlcHandlerOUT( Enable := TRUE );
  MC_FieldbusHandlerOUT( Enable := TRUE );
{Additional_info : 2,1,10000,0,1,4294967295}
END_TASK

TASK TaskPriority (PRIORITY := 2, INTERVAL := T#10ms);
  PRG_TaskPriority();
  PRG_TaskPriority_Kinematics();
  AxisHandler_Priority_MultiMotion();
  TraceHandler();
{Additional_info : 1,0,0,0,1,4294967295}
END_TASK

TASK TaskLowPriority (PRIORITY := 8, INTERVAL := T#100ms);
  PRG_Simu3D_DataExchange_Kinematics();
  MC_MsgHandler();	
{Additional_info : 1,0,0,0,1,4294967295}
END_TASK

{event_task : 'start','Called when program starts','','FUNCTION systemevent: DWORD$R$NVAR_INPUT$R$N$TdwEvent: DWORD;$R$N$TdwFilter: DWORD;$R$N$TdwOwner: DWORD;$R$NEND_VAR$R$N'}{event_task_info : 0,1,24341}
{event_task : 'stop','Called when program stops','','FUNCTION systemevent: DWORD$R$NVAR_INPUT$R$N$TdwEvent: DWORD;$R$N$TdwFilter: DWORD;$R$N$TdwOwner: DWORD;$R$NEND_VAR$R$N'}{event_task_info : 0,2,24341}
{event_task : 'before_reset','Called before reset takes place','','FUNCTION systemevent: DWORD$R$NVAR_INPUT$R$N$TdwEvent: DWORD;$R$N$TdwFilter: DWORD;$R$N$TdwOwner: DWORD;$R$NEND_VAR$R$N'}{event_task_info : 0,3,24341}
{event_task : 'after_reset','Called after reset took place','','FUNCTION systemevent: DWORD$R$NVAR_INPUT$R$N$TdwEvent: DWORD;$R$N$TdwFilter: DWORD;$R$N$TdwOwner: DWORD;$R$NEND_VAR$R$N'}{event_task_info : 0,4,24341}
{event_task : 'shutdown','Called before shutdown is performed','','FUNCTION systemevent: DWORD$R$NVAR_INPUT$R$N$TdwEvent: DWORD;$R$N$TdwFilter: DWORD;$R$N$TdwOwner: DWORD;$R$NEND_VAR$R$N'}{event_task_info : 0,5,24341}
{event_task : 'excpt_cycletime_overflow','Called when a cycletime overflow happened','','FUNCTION systemevent: DWORD$R$NVAR_INPUT$R$N$TdwEvent: DWORD;$R$N$TdwFilter: DWORD;$R$N$TdwOwner: DWORD;$R$NEND_VAR$R$N'}{event_task_info : 0,6,24341}
{event_task : 'excpt_watchdog','Software watchdog OF IEC-task expired','','FUNCTION systemevent: DWORD$R$NVAR_INPUT$R$N$TdwEvent: DWORD;$R$N$TdwFilter: DWORD;$R$N$TdwOwner: DWORD;$R$NEND_VAR$R$N'}{event_task_info : 0,7,24341}

END_RESOURCE




