// ------------------------------------------------------------------------
// Dateiname   : C:\Users\DEWALKAT\Documents\SEW\MotionStudio\AppBuilderProjects\TabellenPosi\PlugInUserControl.event.cs
// ------------------------------------------------------------------------
// Projekt     : ApplicationBuilder.NET Project
// Beschreibung: Autogenerated ApplicationBuilder event handler
// ------------------------------------------------------------------------
// Autor       : autogenerated
// Datum       : Dienstag, 12. Juni 2018
// ------------------------------------------------------------------------
// Verweise
#region used namespaces
using System;
using System.Drawing;
using System.Data;
using System.Xml;
using System.Windows.Forms;
using ApplicationBuilderExtender;
using ApplicationBuilderExtender.Logging;
using ApplicationBuilderExtender.Components;
using SEW.XMLDataServer;
using SEW.Parser;
using SEW.Framework.PlugInDefines;
using SEW.TechEditor.TechEditorBasis;
using SewPlcHandler;
#endregion


namespace AppBuilder.NET
{
  public partial class PlugInUserControl
  {


    // ------------------------------------------------------------------
    // CloseEvent of the application or plugIn
    // ------------------------------------------------------------------
    private void CloseEvent()
    {
      try
      {
        // Please insert code here
      }
      catch(Exception ex)
      {
        // Error handling
        SEW.SEWControls.ControlRe.SewPropertyGridWindow.ShowPropertyGridDialog("Exception:", "Initialisation exception:", ex.Message, ex);
      }
    }


  

    private void handler_fctBtnConfirm_Click(object Value0, System.EventArgs Value1)
    {
      try
      {
        // Please insert code here
      }
      catch(Exception ex)
      {
        // Error handling
        SEW.SEWControls.ControlRe.SewPropertyGridWindow.ShowPropertyGridDialog("Exception:", "Initialisation exception:", ex.Message, ex);
      }
    }



    private void handler_checkBox1_CheckedChanged(object Value0, System.EventArgs Value1)
    {
      try
      {
        // Please insert code here
      }
      catch(Exception ex)
      {
        // Error handling
        SEW.SEWControls.ControlRe.SewPropertyGridWindow.ShowPropertyGridDialog("Exception:", "Initialisation exception:", ex.Message, ex);
      }
    }



    private void handler_checkBox6_CheckedChanged(object Value0, System.EventArgs Value1)
    {
      try
      {
        // Please insert code here
      }
      catch(Exception ex)
      {
        // Error handling
        SEW.SEWControls.ControlRe.SewPropertyGridWindow.ShowPropertyGridDialog("Exception:", "Initialisation exception:", ex.Message, ex);
      }
    }



    private void handler_checkBox5_CheckedChanged(object Value0, System.EventArgs Value1)
    {
      try
      {
        // Please insert code here
      }
      catch(Exception ex)
      {
        // Error handling
        SEW.SEWControls.ControlRe.SewPropertyGridWindow.ShowPropertyGridDialog("Exception:", "Initialisation exception:", ex.Message, ex);
      }
    }



    private void handler_label4_Click(object Value0, System.EventArgs Value1)
    {
      try
      {
        // Please insert code here
      }
      catch(Exception ex)
      {
        // Error handling
        SEW.SEWControls.ControlRe.SewPropertyGridWindow.ShowPropertyGridDialog("Exception:", "Initialisation exception:", ex.Message, ex);
      }
    }



    private void handler_label10_Click(object Value0, System.EventArgs Value1)
    {
      try
      {
        // Please insert code here
      }
      catch(Exception ex)
      {
        // Error handling
        SEW.SEWControls.ControlRe.SewPropertyGridWindow.ShowPropertyGridDialog("Exception:", "Initialisation exception:", ex.Message, ex);
      }
    }



    private void handler_label9_Click(object Value0, System.EventArgs Value1)
    {
      try
      {
        // Please insert code here
      }
      catch(Exception ex)
      {
        // Error handling
        SEW.SEWControls.ControlRe.SewPropertyGridWindow.ShowPropertyGridDialog("Exception:", "Initialisation exception:", ex.Message, ex);
      }
    }



    private void handler_label1_Click(object Value0, System.EventArgs Value1)
    {
      try
      {
        // Please insert code here
      }
      catch(Exception ex)
      {
        // Error handling
        SEW.SEWControls.ControlRe.SewPropertyGridWindow.ShowPropertyGridDialog("Exception:", "Initialisation exception:", ex.Message, ex);
      }
    }

}
}
