

(* @NESTEDCOMMENTS := 'Yes' *)
(* @PATH := '\/AxisGroupControl_Kinematics\/Examples\/Simu3D_Show User Positions' *)
(* @OBJECTFLAGS := '0, 8' *)
(* @SYMFILEFLAGS := '2048' *)
(*##############################################################################################################

	IMPORTANT NOTICE:
 	This example is a special and free service that demonstrates only the basic 
	approach to generating a PLC program as a non-binding sample. 
	SEW is not liable for the contents of the sample program.

	Name:			PRG_Example_UserCoordSystems
	Job:			This example shows, how you can display user defined positions in the 3D Simulation. They are shown as coordinate systems. 

					The struct 'Example_CoordSystems' contains the data for the visualization.
					With the variables 'Example_CoordSystems.CS[1].WCS_XCS[1..6]' you can change the postition of the coordinate systems.
					In the action 'Configuration' you can change the amount of coordinate systems ('Example_CoordSystems.Config.NumberOfCoordSystems') and the names/labels that are displayed in the 3D Simulation.

					Call this Programm in the TaskLowPriority.	

################################################################################################################*)
PROGRAM PRG_UserCoordSystems_Example
VAR

	Example_CoordSystems						 : ST_Simu3D_CoordSystems;	(* Datastructure/Interface for the coordinate systems *)
	fbFB_Simu3D_DataExchange_CoordSys 	 :  FB_Simu3D_DataExchange_CoordSys;	(* This FB manages the communication with the PC/simulation tool *)
	bCoordSystemsConfigured	: BOOL:=FALSE;
	iCoordSysCounter : INT;

END_VAR
(* @END_DECLARATION := '0' *)
IF NOT bCoordSystemsConfigured THEN
	Configuration();
ELSE
	Example_CoordSystems.EnableVisu := TRUE; (* Start the communication with the PC after the configuration is done *)

	Example_CoordSystems.CS[1].WCS_XCS[1] := 50; (* example for changing the position (here only x coordinate) of the first coordinate system *)

	fbFB_Simu3D_DataExchange_CoordSys(CoordSystems := Example_CoordSystems);
END_IF

END_PROGRAM
ACTION	Configuration:
IF AxisGroupKin.ConfigDataAvailable THEN

	Example_CoordSystems.Config.Simu3D_Config.Content1_FileName := ''; (* Do not change. *)
	Example_CoordSystems.Config.Simu3D_Config.Content1_Coding := 138; (* Do not change. *)
	Example_CoordSystems.Config.Simu3D_Config.Content2_Coding := 84; (* Do not change. *)
	Example_CoordSystems.Config.Simu3D_Config.Content2_FileName := 'UserCoordsystems.csb'; (* Do not change. *)
	Example_CoordSystems.Config.Simu3D_Config.WriteDiagToMemoryCard := FALSE; (* Do not change. *)
	Example_CoordSystems.Config.Simu3D_Config.KeepSceneAtLoading := TRUE; (* Do not change. *)

	Example_CoordSystems.Config.strInstanceName := 'Example_UserCoordsystems'; (* Name of the group of coordinate systems which is displayed at bottom left of 3D simulation *)
	Example_CoordSystems.Config.NumberOfCoordSystems := 1; (* Determines how many coordinate systems are display. Maximum amount of coordinate systems  is NUM_OF_USER_COORDSYSTEMS_PER_INSTANCE (= 20) *)

	(* Use the IP-Address and RotUnit of the first Kinematics-Instance *)
	Example_CoordSystems.Config.Simu3D_Config.IP_Address_PC := AxisGroupKin.Inst[1].Config.Simu3D.IP_Address_SimulationPC;
	IF AxisGroupKin.Inst[1].Config.Cart.Use[4] = KIN_USE_DEGR THEN
		Example_CoordSystems.Config.UseDegree := TRUE;
	ELSE
		Example_CoordSystems.Config.UseDegree := FALSE;
	END_IF

	FOR iCoordSysCounter := 1 TO Example_CoordSystems.Config.NumberOfCoordSystems DO
		Example_CoordSystems.CS[iCoordSysCounter].Label := CONCAT('Example_P', INT_TO_STRING(iCoordSysCounter)); (* text displayed at each coordinate sytem *)
	END_FOR

	bCoordSystemsConfigured := TRUE;

END_IF
END_ACTION




(* @NESTEDCOMMENTS := 'Yes' *)
(* @PATH := '\/AxisGroupControl_Kinematics\/Examples' *)
(* @OBJECTFLAGS := '0, 8' *)
(* @SYMFILEFLAGS := '2048' *)
(*##############################################################################################################

	IMPORTANT NOTICE:
 	This example is a special and free service that demonstrates only the basic 
	approach to generating a PLC program as a non-binding sample. 
	SEW is not liable for the contents of the sample program.

	Name:			FB_User_Kinematics_Examples
	Job:			This FB is called in  PRG_TaskMain_Kinematics and calls all the User programs

################################################################################################################*)

FUNCTION_BLOCK FB_User_Kinematics_Examples
VAR
	fbMainCycle_Kinematics	: MainCycle_Kinematics;
	F_TRIG: F_TRIG;

END_VAR
VAR_IN_OUT
	AxisGroupKin_Inst : ST_AxisGroupKin_Instance;				(* AxisGroupControl Interface to application program *)
END_VAR
(* @END_DECLARATION := '0' *)
_FBD_BODY
_NETWORKS : 5
_NETWORK

_COMMENT
'Don$'t run the example programs, if the kinematics instance is not enabled.'
_END_COMMENT
_RET
_EXPRESSION
_POSITIV
_OPERAND
_EXPRESSION
_NEGATIV
AxisGroupKin_Inst.Config.Enable
_NETWORK

_COMMENT
'If the HMIControl is True the UserProgramm must not be executed, because otherwise the KinematicsMonitor has no control over the AxisGroupKin Interface'
_END_COMMENT
_ASSIGN
_OPERAND
_EXPRESSION
_POSITIV
AxisGroupKin.HMI.HMIControl
_EXPRESSION
_POSITIV
_OUTPUTS : 1
_OUTPUT
_NEGATIV
_SET
gKinExamples_Control[AxisGroupKin_Inst.Config.General.InstanceNumber].EnableExamples
_NETWORK

_COMMENT
'At reset of EnableExamples, stop the motion.'
_END_COMMENT
_ASSIGN
_FUNCTIONBLOCK
F_TRIG
_BOX_EXPR : 1
_OPERAND
_EXPRESSION
_POSITIV
gKinExamples_Control[AxisGroupKin_Inst.Config.General.InstanceNumber].EnableExamples
_EXPRESSION
_POSITIV
F_TRIG
_OUTPUTS : 0
_EXPRESSION
_POSITIV
_OUTPUTS : 4
_OUTPUT
_POSITIV
_SET
AxisGroupKin_Inst.In.General.Kin.RapidStop
_OUTPUT
_NEGATIV
_SET
AxisGroupKin_Inst.In.General.Kin.FeedEnable
_OUTPUT
_NEGATIV
_SET
AxisGroupKin_Inst.In.General.Inverter.Enable_Stop[0]
_OUTPUT
_NEGATIV
_SET
AxisGroupKin_Inst.In.General.Inverter.Enable_RapidStop[0]
_NETWORK

_COMMENT
'Don$'t execute any motion sequence before AxisGroupKin.ConfigDataAvailable = TRUE.'
_END_COMMENT
_RET
_EXPRESSION
_POSITIV
_OPERATOR
_BOX_EXPR : 2
_OPERAND
_EXPRESSION
_NEGATIV
gKinExamples_Control[AxisGroupKin_Inst.Config.General.InstanceNumber].EnableExamples
_OPERAND
_EXPRESSION
_NEGATIV
AxisGroupKin.ConfigDataAvailable
_EXPRESSION
_POSITIV
OR
_NETWORK

_COMMENT
''
_END_COMMENT
_FUNCTIONBLOCK
fbMainCycle_Kinematics
_BOX_EXPR : 1
_OPERAND
_EXPRESSION
_POSITIV
AxisGroupKin_Inst
_EXPRESSION
_POSITIV
MainCycle_Kinematics
_OUTPUTS : 0

END_FUNCTION_BLOCK


(* @NESTEDCOMMENTS := 'Yes' *)
(* @PATH := '\/AxisGroupControl_Kinematics\/Examples' *)
(* @OBJECTFLAGS := '0, 8' *)
(* @SYMFILEFLAGS := '2048' *)
(*##############################################################################################################

	IMPORTANT NOTICE:
 	This example is a special and free service that demonstrates only the basic 
	approach to generating a PLC program as a non-binding sample. 
	SEW is not liable for the contents of the sample program.

	Name:			MainCycle_MDX
	Job:			Calls all UserProgramms

################################################################################################################*)
FUNCTION_BLOCK MainCycle_Kinematics
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	fbOperationMode			: OperationMode_Kinematics;
	InstanceNumber				: INT;
	i : INT;
END_VAR
VAR_IN_OUT
	AxisGroupKin_Inst : ST_AxisGroupKin_Instance;				(* AxisGroupControl Interface to application program *)
END_VAR
(* @END_DECLARATION := '0' *)

INITIAL_STEP Init:
InstanceNumber := AxisGroupKin_Inst.Config.General.InstanceNumber;

FOR i := 1 TO 8 DO
	AxisGroupKin_Inst.In.General.Inverter.Enable_RapidStop[i] := FALSE;
	AxisGroupKin_Inst.In.General.Inverter.Enable_Stop[i] := FALSE;
	AxisGroupKin_Inst.In.General.Inverter.Inhibit[i] := FALSE;
END_FOR

END_STEP
(* @SFCMAXTIME := '' *)
(* @SFCMINTIME := '' *)
(* @SFCCOMMENT := '' *)
TRANSITION Connected   FROM Init TO (S90_ControlFunction,S100_LogicFunction,S200_ErrorHandling):= 
_FBD_BODY
_NETWORKS : 1
_NETWORK

_COMMENT
''
_END_COMMENT
_OPERAND
_EXPRESSION
_POSITIV
AxisGroupKin.Inst[InstanceNumber].Out.General.Inverter.Connected[0]


END_TRANSITION
STEP S90_ControlFunction:

AxisGroupKin_Inst.In.General.Inverter.Enable_RapidStop[0]	:= gKinExamples_Control[InstanceNumber].Inverter.Enable_RapidStop_AllAxis;
AxisGroupKin_Inst.In.General.Inverter.Enable_Stop[0] 			:= gKinExamples_Control[InstanceNumber].Inverter.Enable_Stop_AllAxis;
AxisGroupKin_Inst.In.General.Inverter.Inhibit[0]					:= gKinExamples_Control[InstanceNumber].Inverter.Inhibit_AllAxis;

AxisGroupKin_Inst.In.General.Kin.FeedEnable					:= gKinExamples_Control[InstanceNumber].Kin.FeedEnable;
AxisGroupKin_Inst.In.General.Kin.RapidStop					:= gKinExamples_Control[InstanceNumber].Kin.RapidStop;
AxisGroupKin_Inst.In.General.Kin.OverridePercentage			:= gKinExamples_Control[InstanceNumber].Kin.OverridePercentage;

AxisGroupKin_Inst.In.General.Reset 							:= gKinExamples_Control[InstanceNumber].ErrorReset;

END_STEP
(* @SFCMAXTIME := '' *)
(* @SFCMINTIME := '' *)
(* @SFCCOMMENT := '' *)
STEP S100_LogicFunction:
_FBD_BODY
_NETWORKS : 1
_NETWORK

_COMMENT
'In the FB Operation Mode the switch on sequense and running the Sequence Programms is implemented.'
_END_COMMENT
_ASSIGN
_FUNCTIONBLOCK
fbOperationMode
_BOX_EXPR : 5
_OPERAND
_EXPRESSION
_POSITIV
gsSeqMode[InstanceNumber].Reset
_OPERAND
_EXPRESSION
_POSITIV
gsSeqMode[InstanceNumber].Init
_OPERAND
_EXPRESSION
_POSITIV
gsSeqMode[InstanceNumber].EnableLimit
_OPERAND
_EXPRESSION
_POSITIV
gsSeqMode[InstanceNumber].QuitError
_OPERAND
_EXPRESSION
_POSITIV
AxisGroupKin_Inst
_EXPRESSION
_POSITIV
OperationMode_Kinematics
_OUTPUTS : 2
_OUTPUT
_POSITIV
_NO_SET
gsSeqMode[InstanceNumber].Error
_OUTPUT
_POSITIV
_NO_SET
gsSeqMode[InstanceNumber].ErrorStep
_EXPRESSION
_POSITIV
_OUTPUTS : 1
_OUTPUT
_POSITIV
_NO_SET
gsSeqMode[InstanceNumber].CurrentStep


END_STEP
(* @SFCMAXTIME := '' *)
(* @SFCMINTIME := '' *)
(* @SFCCOMMENT := '' *)
STEP S200_ErrorHandling:
_FBD_BODY
_NETWORKS : 1
_NETWORK

_COMMENT
''
_END_COMMENT
_OPERAND
_EXPRESSION
_POSITIV
TRUE


END_STEP
(* @SFCMAXTIME := '' *)
(* @SFCMINTIME := '' *)
(* @SFCCOMMENT := '' *)
TRANSITION FROM (S90_ControlFunction,S100_LogicFunction,S200_ErrorHandling) TO Init:= 
FALSE


END_TRANSITION

END_FUNCTION_BLOCK


(* @NESTEDCOMMENTS := 'Yes' *)
(* @PATH := '\/AxisGroupControl_Kinematics\/Examples' *)
(* @OBJECTFLAGS := '0, 8' *)
(* @SYMFILEFLAGS := '2048' *)
(*##############################################################################################################

	IMPORTANT NOTICE:
 	This example is a special and free service that demonstrates only the basic 
	approach to generating a PLC program as a non-binding sample. 
	SEW is not liable for the contents of the sample program.

	Name:			OperationMode
	Job:			Calls all kinematics example programs

################################################################################################################*)
FUNCTION_BLOCK OperationMode_Kinematics
VAR_INPUT
	SFCReset:						 BOOL;									(*This variable, of type BOOL, behaves similarly to SFCInit. Unlike the latter, however,
																				further processing takes place after the initialization of the Init step.
																				Thus for example the SFCReset flag could be re-set to FALSE in the Init step.*)

	SFCInit:							 BOOL;									(*When this boolean variable has the value TRUE the sequential function chart is set back
																				to the Init step. The other SFC flags are reset too (initialization).
																				The Init step remains active, but is not executed, for as long as the variable has the value TRUE.
																				It is only when SFCInit is again set to FALSE that the block can be processed normally.*)
	SFCEnableLimit:					BOOL;									(*This variable is of the type BOOL. When it has the value TRUE, the timeouts of the
																				steps will be registered in SFCError. Other timeouts will be ignored.*)
	SFCQuitError: 						BOOL;									(*Provided that the Execution of the SFC diagram is stopped for as long as this boolean
																				variable has the value TRUE whereby a possible timeout in the variable SFCError is reset. All
																				previous times in the active steps are reset when the variable again assumes the value FALSE. It is a
																				pre-condition that the flag SFCError has been defined also, which registers any timeout in the SFC.*)
END_VAR
VAR_OUTPUT
	SFCCurrentStep:					 STRING;								(*This variable is of the type STRING.
																				The name of the step is stored in this variable which is active, independently of the time monitoring.
																				In the case of simultaneous sequences the step is stored in the branch on the outer right.*)
	SFCError: 							BOOL;									(*This Boolean variable is TRUE when a timeout has occurred in a SFC diagram. If another
																				timeout occurs in a program after the first one, it will not be registered unless the variable SFCError is
																				reset first. It is a pre-condition that SFCError is defined, if you want to use the other time-controlling
																				flags (SFCErrorStep, SFCErrorPOU, SFCQuitError, SFCErrorAnalyzation).*)
	SFCErrorStep: 					STRING; 								(*This variable is of the type STRING. If SFCError registers a timeout, in this variable is
																				stored the name of the step which has caused the timeout. It is a pre-condition that the flag SFCError
																				has been defined also, which registers any timeout in the SFC. *)
END_VAR
VAR_IN_OUT
	AxisGroupKin_Inst				: ST_AxisGroupKin_Instance;				(* AxisGroupControl Interface to application program *)
END_VAR
VAR
	fbPRG_XYZ_PICKnPLACE_ST							: PRG01_XYZ_PICKnPLACE_ST;
	fbPRG_XYZ_PICKnPLACE_SFC							: PRG02_XYZ_PICKnPLACE_SFC;
	fbPRG_XYZ_TARG_LIN_CIRC_ST						: PRG03_XYZ_TARG_LIN_CIRC_ST;
	fbPRG_XYZ_TARG_LIN_CIRC_SFC						: PRG04_XYZ_TARG_LIN_CIRC_SFC;
	fbPRG_XYZ_FillQueue_LIN3D_with_Array_ST			: PRG05_XYZ_FillQueue_LIN3D_with_Array_ST;
	fbPRG_XYZ_FillQueue_LIN3D_with_Array_SFC		: PRG06_XYZ_FillQueue_LIN3D_with_Array_SFC;
	fbPRG_XYZ_USER_ST									: PRG07_XYZ_USER_ST;
	fbPRG_XYZ_USER_SFC									: PRG08_XYZ_USER_SFC;
	InstanceNumber: INT;
END_VAR
(* @END_DECLARATION := '0' *)

INITIAL_STEP S000_Init:

InstanceNumber							:= AxisGroupKin_Inst.Config.General.InstanceNumber;
gsSeqMode[InstanceNumber].Reset	:= FALSE;


END_STEP
(* @SFCMAXTIME := '' *)
(* @SFCMINTIME := '' *)
(* @SFCCOMMENT := '' *)
TRANSITION NOT referenced   FROM S000_Init TO S050_Homing:= 
_FBD_BODY
_NETWORKS : 1
_NETWORK

_COMMENT
''
_END_COMMENT
_OPERATOR
_BOX_EXPR : 2
_OPERAND
_EXPRESSION
_POSITIV
AxisGroupKin_Inst.Out.General.Inverter.Connected[0]
_OPERAND
_EXPRESSION
_NEGATIV
AxisGroupKin_Inst.Out.General.Inverter.Referenced[0]
_EXPRESSION
_POSITIV
AND


END_TRANSITION
TRANSITION referenced   FROM S000_Init TO S051_Not_Homing:= 
_FBD_BODY
_NETWORKS : 1
_NETWORK

_COMMENT
''
_END_COMMENT
_OPERATOR
_BOX_EXPR : 2
_OPERAND
_EXPRESSION
_POSITIV
AxisGroupKin_Inst.Out.General.Inverter.Connected[0]
_OPERAND
_EXPRESSION
_POSITIV
AxisGroupKin_Inst.Out.General.Inverter.Referenced[0]
_EXPRESSION
_POSITIV
AND


END_TRANSITION
STEP S051_Not_Homing:
_FBD_BODY
_NETWORKS : 0


END_STEP
(* @SFCMAXTIME := '' *)
(* @SFCMINTIME := '' *)
(* @SFCCOMMENT := '' *)
TRANSITION FROM S051_Not_Homing TO S100_Mode_Select:= 
TRUE


END_TRANSITION
STEP S050_Homing:
_FBD_BODY
_NETWORKS : 1
_NETWORK

_COMMENT
'Action for Homing'
_END_COMMENT
_OPERAND
_EXPRESSION
_POSITIV
TRUE


END_STEP
(* @SFCMAXTIME := '' *)
(* @SFCMINTIME := '' *)
(* @SFCCOMMENT := '' *)
ENTRY_ACTION	
_FBD_BODY
_NETWORKS : 2
_NETWORK

_COMMENT
'Entry Action for Homing'
_END_COMMENT
_OPERAND
_EXPRESSION
_POSITIV
FALSE
_NETWORK

_COMMENT
''
_END_COMMENT
_ASSIGN
_OPERAND
_EXPRESSION
_POSITIV
TRUE
_EXPRESSION
_POSITIV
_OUTPUTS : 1
_OUTPUT
_POSITIV
_NO_SET
AxisGroupKin_Inst.In.General.Inverter.Inhibit[0]

END_ACTION

EXIT_ACTION	
_FBD_BODY
_NETWORKS : 1
_NETWORK

_COMMENT
''
_END_COMMENT
_ASSIGN
_OPERAND
_EXPRESSION
_POSITIV
TRUE
_EXPRESSION
_POSITIV
_OUTPUTS : 1
_OUTPUT
_POSITIV
_NO_SET
AxisGroupKin_Inst.In.General.Inverter.Inhibit[0]

END_ACTION

TRANSITION Homing done   FROM S050_Homing TO S100_Mode_Select:= 
_FBD_BODY
_NETWORKS : 1
_NETWORK

_COMMENT
''
_END_COMMENT
_OPERATOR
_BOX_EXPR : 2
_OPERAND
_EXPRESSION
_POSITIV
AxisGroupKin_Inst.Out.General.Inverter.Connected[0]
_OPERAND
_EXPRESSION
_POSITIV
AxisGroupKin_Inst.Out.General.Inverter.Referenced[0]
_EXPRESSION
_POSITIV
AND


END_TRANSITION
STEP S100_Mode_Select:
(* @TEXT_IMPLEMENTATION := 'ST' *)
AxisGroupKin_Inst.In.General.Mode:=KIN_STOP;

END_STEP
(* @SFCMAXTIME := '' *)
(* @SFCMINTIME := '' *)
(* @SFCCOMMENT := '' *)
TRANSITION Automatic Mode   FROM S100_Mode_Select TO S100_Waiting_for_Start:= 
_FBD_BODY
_NETWORKS : 1
_NETWORK

_COMMENT
''
_END_COMMENT
_OPERAND
_EXPRESSION
_POSITIV
AxisGroupKin_Inst.Out.General.Kin.Ready


END_TRANSITION
TRANSITION Jog Mode   FROM S100_Mode_Select TO S700_ManualMode:= 
_FBD_BODY
_NETWORKS : 1
_NETWORK

_COMMENT
''
_END_COMMENT
_OPERAND
_EXPRESSION
_NEGATIV
FALSE


END_TRANSITION
STEP S700_ManualMode:
(* @TEXT_IMPLEMENTATION := 'ST' *)
;

END_STEP
(* @SFCMAXTIME := '' *)
(* @SFCMINTIME := '' *)
(* @SFCCOMMENT := '' *)
TRANSITION no Jog Mode   FROM S700_ManualMode TO S100_Mode_Select:= 
_FBD_BODY
_NETWORKS : 1
_NETWORK

_COMMENT
''
_END_COMMENT
_OPERAND
_EXPRESSION
_POSITIV
FALSE


END_TRANSITION
STEP S100_Waiting_for_Start:
(* @TEXT_IMPLEMENTATION := 'ST' *)
;

END_STEP
(* @SFCMAXTIME := '' *)
(* @SFCMINTIME := '' *)
(* @SFCCOMMENT := '' *)
TRANSITION Start AND Enabled   FROM S100_Waiting_for_Start TO S200_AutomaticMode:= 
_FBD_BODY
_NETWORKS : 1
_NETWORK

_COMMENT
''
_END_COMMENT
_OPERATOR
_BOX_EXPR : 2
_OPERAND
_EXPRESSION
_POSITIV
TRUE
_OPERAND
_EXPRESSION
_POSITIV
AxisGroupKin_Inst.Out.General.Kin.Ready
_EXPRESSION
_POSITIV
AND


END_TRANSITION
STEP S200_AutomaticMode:
_FBD_BODY
_NETWORKS : 0


END_STEP
(* @SFCMAXTIME := '' *)
(* @SFCMINTIME := '' *)
(* @SFCCOMMENT := '' *)
TRANSITION PRG1_Pick_and_Place_ST   FROM S200_AutomaticMode TO S250_XYZ_PICKnPLACE_ST:= 
_FBD_BODY
_NETWORKS : 1
_NETWORK

_COMMENT
''
_END_COMMENT
_OPERATOR
_BOX_EXPR : 2
_OPERAND
_EXPRESSION
_POSITIV
gKinExamples_Control[InstanceNumber].ProgramNumber
_OPERAND
_EXPRESSION
_POSITIV
1
_EXPRESSION
_POSITIV
EQ


END_TRANSITION
TRANSITION Pick_and_Place_SFC   FROM S200_AutomaticMode TO S300_XYZ_PICKnPLACE_SFC:= 
_FBD_BODY
_NETWORKS : 1
_NETWORK

_COMMENT
''
_END_COMMENT
_OPERATOR
_BOX_EXPR : 2
_OPERAND
_EXPRESSION
_POSITIV
gKinExamples_Control[InstanceNumber].ProgramNumber
_OPERAND
_EXPRESSION
_POSITIV
2
_EXPRESSION
_POSITIV
EQ


END_TRANSITION
STEP S300_XYZ_PICKnPLACE_SFC:
_FBD_BODY
_NETWORKS : 1
_NETWORK

_COMMENT
''
_END_COMMENT
_FUNCTIONBLOCK
fbPRG_XYZ_PICKnPLACE_SFC
_BOX_EXPR : 7
_OPERAND
_EXPRESSION
_POSITIV
FALSE
_OPERAND
_EXPRESSION
_POSITIV
FALSE
_OPERAND
_EXPRESSION
_POSITIV
FALSE
_OPERAND
_EXPRESSION
_POSITIV
FALSE
_OPERAND
_EXPRESSION
_POSITIV
FALSE
_OPERAND
_EXPRESSION
_POSITIV
FALSE
_OPERAND
_EXPRESSION
_POSITIV
AxisGroupKin_Inst
_EXPRESSION
_POSITIV
PRG02_XYZ_PICKnPLACE_SFC
_OUTPUTS : 5
_OUTPUT
_POSITIV
_NO_SET
_EMPTY
_OUTPUT
_POSITIV
_NO_SET
_EMPTY
_OUTPUT
_POSITIV
_NO_SET
_EMPTY
_OUTPUT
_POSITIV
_NO_SET
_EMPTY
_OUTPUT
_POSITIV
_NO_SET
_EMPTY


END_STEP
(* @SFCMAXTIME := '' *)
(* @SFCMINTIME := '' *)
(* @SFCCOMMENT := '' *)
ENTRY_ACTION	
_FBD_BODY
_NETWORKS : 1
_NETWORK

_COMMENT
''
_END_COMMENT
_FUNCTIONBLOCK
fbPRG_XYZ_PICKnPLACE_SFC
_BOX_EXPR : 7
_OPERAND
_EXPRESSION
_POSITIV
TRUE
_OPERAND
_EXPRESSION
_POSITIV
TRUE
_OPERAND
_EXPRESSION
_POSITIV
FALSE
_OPERAND
_EXPRESSION
_POSITIV
FALSE
_OPERAND
_EXPRESSION
_POSITIV
FALSE
_OPERAND
_EXPRESSION
_POSITIV
FALSE
_OPERAND
_EXPRESSION
_POSITIV
AxisGroupKin_Inst
_EXPRESSION
_POSITIV
PRG02_XYZ_PICKnPLACE_SFC
_OUTPUTS : 5
_OUTPUT
_POSITIV
_NO_SET
_EMPTY
_OUTPUT
_POSITIV
_NO_SET
_EMPTY
_OUTPUT
_POSITIV
_NO_SET
_EMPTY
_OUTPUT
_POSITIV
_NO_SET
_EMPTY
_OUTPUT
_POSITIV
_NO_SET
_EMPTY

END_ACTION

TRANSITION new Mode or Done   FROM S300_XYZ_PICKnPLACE_SFC TO S000_Init:= 
_FBD_BODY
_NETWORKS : 1
_NETWORK

_COMMENT
''
_END_COMMENT
_OPERATOR
_BOX_EXPR : 2
_OPERATOR
_BOX_EXPR : 2
_OPERAND
_EXPRESSION
_POSITIV
gKinExamples_Control[InstanceNumber].ProgramNumber
_OPERAND
_EXPRESSION
_POSITIV
2
_EXPRESSION
_POSITIV
NE
_OPERAND
_EXPRESSION
_POSITIV
fbPRG_XYZ_PICKnPLACE_SFC.Done
_EXPRESSION
_POSITIV
OR


END_TRANSITION
TRANSITION XYZ_TARG_LIN_CIRC_ST   FROM S200_AutomaticMode TO S350_XYZ_TARG_LIN_CIRC_ST:= 
_FBD_BODY
_NETWORKS : 1
_NETWORK

_COMMENT
''
_END_COMMENT
_OPERATOR
_BOX_EXPR : 2
_OPERAND
_EXPRESSION
_POSITIV
gKinExamples_Control[InstanceNumber].ProgramNumber
_OPERAND
_EXPRESSION
_POSITIV
3
_EXPRESSION
_POSITIV
EQ


END_TRANSITION
STEP S350_XYZ_TARG_LIN_CIRC_ST:
_FBD_BODY
_NETWORKS : 1
_NETWORK

_COMMENT
''
_END_COMMENT
_FUNCTIONBLOCK
fbPRG_XYZ_TARG_LIN_CIRC_ST
_BOX_EXPR : 2
_OPERAND
_EXPRESSION
_POSITIV
TRUE
_OPERAND
_EXPRESSION
_POSITIV
AxisGroupKin_Inst
_EXPRESSION
_POSITIV
PRG03_XYZ_TARG_LIN_CIRC_ST
_OUTPUTS : 1
_OUTPUT
_POSITIV
_NO_SET
_EMPTY


END_STEP
(* @SFCMAXTIME := '' *)
(* @SFCMINTIME := '' *)
(* @SFCCOMMENT := '' *)
ENTRY_ACTION	
_FBD_BODY
_NETWORKS : 1
_NETWORK

_COMMENT
''
_END_COMMENT
_FUNCTIONBLOCK
fbPRG_XYZ_TARG_LIN_CIRC_ST
_BOX_EXPR : 2
_OPERAND
_EXPRESSION
_POSITIV
FALSE
_OPERAND
_EXPRESSION
_POSITIV
AxisGroupKin_Inst
_EXPRESSION
_POSITIV
PRG03_XYZ_TARG_LIN_CIRC_ST
_OUTPUTS : 1
_OUTPUT
_POSITIV
_NO_SET
_EMPTY

END_ACTION

TRANSITION new Mode or Done   FROM S350_XYZ_TARG_LIN_CIRC_ST TO S000_Init:= 
_FBD_BODY
_NETWORKS : 1
_NETWORK

_COMMENT
''
_END_COMMENT
_OPERATOR
_BOX_EXPR : 2
_OPERATOR
_BOX_EXPR : 2
_OPERAND
_EXPRESSION
_POSITIV
gKinExamples_Control[InstanceNumber].ProgramNumber
_OPERAND
_EXPRESSION
_POSITIV
3
_EXPRESSION
_POSITIV
NE
_OPERAND
_EXPRESSION
_POSITIV
fbPRG_XYZ_TARG_LIN_CIRC_ST.Done
_EXPRESSION
_POSITIV
OR


END_TRANSITION
TRANSITION XYZ_TARG_LIN_CIRC_SFC   FROM S200_AutomaticMode TO S400_XYZ_TARG_LIN_CIRC_SFC:= 
_FBD_BODY
_NETWORKS : 1
_NETWORK

_COMMENT
''
_END_COMMENT
_OPERATOR
_BOX_EXPR : 2
_OPERAND
_EXPRESSION
_POSITIV
gKinExamples_Control[InstanceNumber].ProgramNumber
_OPERAND
_EXPRESSION
_POSITIV
4
_EXPRESSION
_POSITIV
EQ


END_TRANSITION
STEP S400_XYZ_TARG_LIN_CIRC_SFC:
_FBD_BODY
_NETWORKS : 1
_NETWORK

_COMMENT
''
_END_COMMENT
_FUNCTIONBLOCK
fbPRG_XYZ_TARG_LIN_CIRC_SFC
_BOX_EXPR : 7
_OPERAND
_EXPRESSION
_POSITIV
FALSE
_OPERAND
_EXPRESSION
_POSITIV
FALSE
_OPERAND
_EXPRESSION
_POSITIV
FALSE
_OPERAND
_EXPRESSION
_POSITIV
FALSE
_OPERAND
_EXPRESSION
_POSITIV
FALSE
_OPERAND
_EXPRESSION
_POSITIV
FALSE
_OPERAND
_EXPRESSION
_POSITIV
AxisGroupKin_Inst
_EXPRESSION
_POSITIV
PRG04_XYZ_TARG_LIN_CIRC_SFC
_OUTPUTS : 5
_OUTPUT
_POSITIV
_NO_SET
_EMPTY
_OUTPUT
_POSITIV
_NO_SET
_EMPTY
_OUTPUT
_POSITIV
_NO_SET
_EMPTY
_OUTPUT
_POSITIV
_NO_SET
_EMPTY
_OUTPUT
_POSITIV
_NO_SET
_EMPTY


END_STEP
(* @SFCMAXTIME := '' *)
(* @SFCMINTIME := '' *)
(* @SFCCOMMENT := '' *)
ENTRY_ACTION	
_FBD_BODY
_NETWORKS : 1
_NETWORK

_COMMENT
''
_END_COMMENT
_FUNCTIONBLOCK
fbPRG_XYZ_TARG_LIN_CIRC_SFC
_BOX_EXPR : 7
_OPERAND
_EXPRESSION
_POSITIV
TRUE
_OPERAND
_EXPRESSION
_POSITIV
TRUE
_OPERAND
_EXPRESSION
_POSITIV
FALSE
_OPERAND
_EXPRESSION
_POSITIV
FALSE
_OPERAND
_EXPRESSION
_POSITIV
FALSE
_OPERAND
_EXPRESSION
_POSITIV
FALSE
_OPERAND
_EXPRESSION
_POSITIV
AxisGroupKin_Inst
_EXPRESSION
_POSITIV
PRG04_XYZ_TARG_LIN_CIRC_SFC
_OUTPUTS : 5
_OUTPUT
_POSITIV
_NO_SET
_EMPTY
_OUTPUT
_POSITIV
_NO_SET
_EMPTY
_OUTPUT
_POSITIV
_NO_SET
_EMPTY
_OUTPUT
_POSITIV
_NO_SET
_EMPTY
_OUTPUT
_POSITIV
_NO_SET
_EMPTY

END_ACTION

TRANSITION new Mode or Done   FROM S400_XYZ_TARG_LIN_CIRC_SFC TO S000_Init:= 
_FBD_BODY
_NETWORKS : 1
_NETWORK

_COMMENT
''
_END_COMMENT
_OPERATOR
_BOX_EXPR : 2
_OPERATOR
_BOX_EXPR : 2
_OPERAND
_EXPRESSION
_POSITIV
gKinExamples_Control[InstanceNumber].ProgramNumber
_OPERAND
_EXPRESSION
_POSITIV
4
_EXPRESSION
_POSITIV
NE
_OPERAND
_EXPRESSION
_POSITIV
fbPRG_XYZ_TARG_LIN_CIRC_SFC.Done
_EXPRESSION
_POSITIV
OR


END_TRANSITION
TRANSITION XYZ_USER_ST   FROM S200_AutomaticMode TO S450_XYZ_USER_ST:= 
_FBD_BODY
_NETWORKS : 1
_NETWORK

_COMMENT
''
_END_COMMENT
_OPERATOR
_BOX_EXPR : 2
_OPERAND
_EXPRESSION
_POSITIV
gKinExamples_Control[InstanceNumber].ProgramNumber
_OPERAND
_EXPRESSION
_POSITIV
7
_EXPRESSION
_POSITIV
EQ


END_TRANSITION
STEP S450_XYZ_USER_ST:
_FBD_BODY
_NETWORKS : 1
_NETWORK

_COMMENT
''
_END_COMMENT
_FUNCTIONBLOCK
fbPRG_XYZ_USER_ST
_BOX_EXPR : 2
_OPERAND
_EXPRESSION
_POSITIV
TRUE
_OPERAND
_EXPRESSION
_POSITIV
AxisGroupKin_Inst
_EXPRESSION
_POSITIV
PRG07_XYZ_USER_ST
_OUTPUTS : 1
_OUTPUT
_POSITIV
_NO_SET
_EMPTY


END_STEP
(* @SFCMAXTIME := '' *)
(* @SFCMINTIME := '' *)
(* @SFCCOMMENT := '' *)
ENTRY_ACTION	
_FBD_BODY
_NETWORKS : 1
_NETWORK

_COMMENT
''
_END_COMMENT
_FUNCTIONBLOCK
fbPRG_XYZ_USER_ST
_BOX_EXPR : 2
_OPERAND
_EXPRESSION
_POSITIV
FALSE
_OPERAND
_EXPRESSION
_POSITIV
AxisGroupKin_Inst
_EXPRESSION
_POSITIV
PRG07_XYZ_USER_ST
_OUTPUTS : 1
_OUTPUT
_POSITIV
_NO_SET
_EMPTY

END_ACTION

TRANSITION new Mode or Done   FROM S450_XYZ_USER_ST TO S000_Init:= 
_FBD_BODY
_NETWORKS : 1
_NETWORK

_COMMENT
''
_END_COMMENT
_OPERATOR
_BOX_EXPR : 2
_OPERATOR
_BOX_EXPR : 2
_OPERAND
_EXPRESSION
_POSITIV
gKinExamples_Control[InstanceNumber].ProgramNumber
_OPERAND
_EXPRESSION
_POSITIV
7
_EXPRESSION
_POSITIV
NE
_OPERAND
_EXPRESSION
_POSITIV
fbPRG_XYZ_USER_ST.Done
_EXPRESSION
_POSITIV
OR


END_TRANSITION
TRANSITION XYZ_USER_SFC   FROM S200_AutomaticMode TO S500_XYZ_USER_SFC:= 
_FBD_BODY
_NETWORKS : 1
_NETWORK

_COMMENT
''
_END_COMMENT
_OPERATOR
_BOX_EXPR : 2
_OPERAND
_EXPRESSION
_POSITIV
gKinExamples_Control[InstanceNumber].ProgramNumber
_OPERAND
_EXPRESSION
_POSITIV
8
_EXPRESSION
_POSITIV
EQ


END_TRANSITION
STEP S500_XYZ_USER_SFC:
_FBD_BODY
_NETWORKS : 1
_NETWORK

_COMMENT
''
_END_COMMENT
_FUNCTIONBLOCK
fbPRG_XYZ_USER_SFC
_BOX_EXPR : 7
_OPERAND
_EXPRESSION
_POSITIV
FALSE
_OPERAND
_EXPRESSION
_POSITIV
FALSE
_OPERAND
_EXPRESSION
_POSITIV
FALSE
_OPERAND
_EXPRESSION
_POSITIV
FALSE
_OPERAND
_EXPRESSION
_POSITIV
FALSE
_OPERAND
_EXPRESSION
_POSITIV
FALSE
_OPERAND
_EXPRESSION
_POSITIV
AxisGroupKin_Inst
_EXPRESSION
_POSITIV
PRG08_XYZ_USER_SFC
_OUTPUTS : 5
_OUTPUT
_POSITIV
_NO_SET
_EMPTY
_OUTPUT
_POSITIV
_NO_SET
_EMPTY
_OUTPUT
_POSITIV
_NO_SET
_EMPTY
_OUTPUT
_POSITIV
_NO_SET
_EMPTY
_OUTPUT
_POSITIV
_NO_SET
_EMPTY


END_STEP
(* @SFCMAXTIME := '' *)
(* @SFCMINTIME := '' *)
(* @SFCCOMMENT := '' *)
ENTRY_ACTION	
_FBD_BODY
_NETWORKS : 1
_NETWORK

_COMMENT
''
_END_COMMENT
_FUNCTIONBLOCK
fbPRG_XYZ_USER_SFC
_BOX_EXPR : 7
_OPERAND
_EXPRESSION
_POSITIV
TRUE
_OPERAND
_EXPRESSION
_POSITIV
TRUE
_OPERAND
_EXPRESSION
_POSITIV
FALSE
_OPERAND
_EXPRESSION
_POSITIV
FALSE
_OPERAND
_EXPRESSION
_POSITIV
FALSE
_OPERAND
_EXPRESSION
_POSITIV
FALSE
_OPERAND
_EXPRESSION
_POSITIV
AxisGroupKin_Inst
_EXPRESSION
_POSITIV
PRG08_XYZ_USER_SFC
_OUTPUTS : 5
_OUTPUT
_POSITIV
_NO_SET
_EMPTY
_OUTPUT
_POSITIV
_NO_SET
_EMPTY
_OUTPUT
_POSITIV
_NO_SET
_EMPTY
_OUTPUT
_POSITIV
_NO_SET
_EMPTY
_OUTPUT
_POSITIV
_NO_SET
_EMPTY

END_ACTION

TRANSITION new Mode or Done   FROM S500_XYZ_USER_SFC TO S000_Init:= 
_FBD_BODY
_NETWORKS : 1
_NETWORK

_COMMENT
''
_END_COMMENT
_OPERATOR
_BOX_EXPR : 2
_OPERATOR
_BOX_EXPR : 2
_OPERAND
_EXPRESSION
_POSITIV
gKinExamples_Control[InstanceNumber].ProgramNumber
_OPERAND
_EXPRESSION
_POSITIV
8
_EXPRESSION
_POSITIV
NE
_OPERAND
_EXPRESSION
_POSITIV
fbPRG_XYZ_USER_SFC.Done
_EXPRESSION
_POSITIV
OR


END_TRANSITION
TRANSITION FillQueue_LIN3D_with_Array_ST   FROM S200_AutomaticMode TO S550_XYZ_FillQueue_LIN3D_with_Array_ST:= 
_FBD_BODY
_NETWORKS : 1
_NETWORK

_COMMENT
''
_END_COMMENT
_OPERATOR
_BOX_EXPR : 2
_OPERAND
_EXPRESSION
_POSITIV
gKinExamples_Control[InstanceNumber].ProgramNumber
_OPERAND
_EXPRESSION
_POSITIV
5
_EXPRESSION
_POSITIV
EQ


END_TRANSITION
STEP S550_XYZ_FillQueue_LIN3D_with_Array_ST:
_FBD_BODY
_NETWORKS : 1
_NETWORK

_COMMENT
''
_END_COMMENT
_FUNCTIONBLOCK
fbPRG_XYZ_FillQueue_LIN3D_with_Array_ST
_BOX_EXPR : 2
_OPERAND
_EXPRESSION
_POSITIV
TRUE
_OPERAND
_EXPRESSION
_POSITIV
AxisGroupKin_Inst
_EXPRESSION
_POSITIV
PRG05_XYZ_FillQueue_LIN3D_with_Array_ST
_OUTPUTS : 1
_OUTPUT
_POSITIV
_NO_SET
_EMPTY


END_STEP
(* @SFCMAXTIME := '' *)
(* @SFCMINTIME := '' *)
(* @SFCCOMMENT := '' *)
ENTRY_ACTION	
_FBD_BODY
_NETWORKS : 1
_NETWORK

_COMMENT
''
_END_COMMENT
_FUNCTIONBLOCK
fbPRG_XYZ_FillQueue_LIN3D_with_Array_ST
_BOX_EXPR : 2
_OPERAND
_EXPRESSION
_POSITIV
FALSE
_OPERAND
_EXPRESSION
_POSITIV
AxisGroupKin_Inst
_EXPRESSION
_POSITIV
PRG05_XYZ_FillQueue_LIN3D_with_Array_ST
_OUTPUTS : 1
_OUTPUT
_POSITIV
_NO_SET
_EMPTY

END_ACTION

TRANSITION new Mode or Done   FROM S550_XYZ_FillQueue_LIN3D_with_Array_ST TO S000_Init:= 
_FBD_BODY
_NETWORKS : 1
_NETWORK

_COMMENT
''
_END_COMMENT
_OPERATOR
_BOX_EXPR : 2
_OPERATOR
_BOX_EXPR : 2
_OPERAND
_EXPRESSION
_POSITIV
gKinExamples_Control[InstanceNumber].ProgramNumber
_OPERAND
_EXPRESSION
_POSITIV
5
_EXPRESSION
_POSITIV
NE
_OPERAND
_EXPRESSION
_POSITIV
fbPRG_XYZ_FillQueue_LIN3D_with_Array_ST.Done
_EXPRESSION
_POSITIV
OR


END_TRANSITION
TRANSITION FillQueue_LIN3D_with_Array_SFC   FROM S200_AutomaticMode TO S600_XYZ_FillQueue_LIN3D_with_Array_SFC:= 
_FBD_BODY
_NETWORKS : 1
_NETWORK

_COMMENT
''
_END_COMMENT
_OPERATOR
_BOX_EXPR : 2
_OPERAND
_EXPRESSION
_POSITIV
gKinExamples_Control[InstanceNumber].ProgramNumber
_OPERAND
_EXPRESSION
_POSITIV
6
_EXPRESSION
_POSITIV
EQ


END_TRANSITION
STEP S600_XYZ_FillQueue_LIN3D_with_Array_SFC:
_FBD_BODY
_NETWORKS : 1
_NETWORK

_COMMENT
''
_END_COMMENT
_FUNCTIONBLOCK
fbPRG_XYZ_FillQueue_LIN3D_with_Array_SFC
_BOX_EXPR : 7
_OPERAND
_EXPRESSION
_POSITIV
FALSE
_OPERAND
_EXPRESSION
_POSITIV
FALSE
_OPERAND
_EXPRESSION
_POSITIV
FALSE
_OPERAND
_EXPRESSION
_POSITIV
FALSE
_OPERAND
_EXPRESSION
_POSITIV
FALSE
_OPERAND
_EXPRESSION
_POSITIV
FALSE
_OPERAND
_EXPRESSION
_POSITIV
AxisGroupKin_Inst
_EXPRESSION
_POSITIV
PRG06_XYZ_FillQueue_LIN3D_with_Array_SFC
_OUTPUTS : 5
_OUTPUT
_POSITIV
_NO_SET
_EMPTY
_OUTPUT
_POSITIV
_NO_SET
_EMPTY
_OUTPUT
_POSITIV
_NO_SET
_EMPTY
_OUTPUT
_POSITIV
_NO_SET
_EMPTY
_OUTPUT
_POSITIV
_NO_SET
_EMPTY


END_STEP
(* @SFCMAXTIME := '' *)
(* @SFCMINTIME := '' *)
(* @SFCCOMMENT := '' *)
ENTRY_ACTION	
_FBD_BODY
_NETWORKS : 1
_NETWORK

_COMMENT
''
_END_COMMENT
_FUNCTIONBLOCK
fbPRG_XYZ_FillQueue_LIN3D_with_Array_SFC
_BOX_EXPR : 7
_OPERAND
_EXPRESSION
_POSITIV
TRUE
_OPERAND
_EXPRESSION
_POSITIV
TRUE
_OPERAND
_EXPRESSION
_POSITIV
FALSE
_OPERAND
_EXPRESSION
_POSITIV
FALSE
_OPERAND
_EXPRESSION
_POSITIV
FALSE
_OPERAND
_EXPRESSION
_POSITIV
FALSE
_OPERAND
_EXPRESSION
_POSITIV
AxisGroupKin_Inst
_EXPRESSION
_POSITIV
PRG06_XYZ_FillQueue_LIN3D_with_Array_SFC
_OUTPUTS : 5
_OUTPUT
_POSITIV
_NO_SET
_EMPTY
_OUTPUT
_POSITIV
_NO_SET
_EMPTY
_OUTPUT
_POSITIV
_NO_SET
_EMPTY
_OUTPUT
_POSITIV
_NO_SET
_EMPTY
_OUTPUT
_POSITIV
_NO_SET
_EMPTY

END_ACTION

TRANSITION new Mode OR Done   FROM S600_XYZ_FillQueue_LIN3D_with_Array_SFC TO S000_Init:= 
_FBD_BODY
_NETWORKS : 1
_NETWORK

_COMMENT
''
_END_COMMENT
_OPERATOR
_BOX_EXPR : 2
_OPERATOR
_BOX_EXPR : 2
_OPERAND
_EXPRESSION
_POSITIV
gKinExamples_Control[InstanceNumber].ProgramNumber
_OPERAND
_EXPRESSION
_POSITIV
6
_EXPRESSION
_POSITIV
NE
_OPERAND
_EXPRESSION
_POSITIV
fbPRG_XYZ_FillQueue_LIN3D_with_Array_SFC.Done
_EXPRESSION
_POSITIV
OR


END_TRANSITION
TRANSITION Jog Mode   FROM S200_AutomaticMode TO S100_Mode_Select:= 
_FBD_BODY
_NETWORKS : 1
_NETWORK

_COMMENT
''
_END_COMMENT
_OPERAND
_EXPRESSION
_NEGATIV
FALSE


END_TRANSITION
STEP S250_XYZ_PICKnPLACE_ST:
_FBD_BODY
_NETWORKS : 1
_NETWORK

_COMMENT
''
_END_COMMENT
_FUNCTIONBLOCK
fbPRG_XYZ_PICKnPLACE_ST
_BOX_EXPR : 2
_OPERAND
_EXPRESSION
_POSITIV
TRUE
_OPERAND
_EXPRESSION
_POSITIV
AxisGroupKin_Inst
_EXPRESSION
_POSITIV
PRG01_XYZ_PICKnPLACE_ST
_OUTPUTS : 1
_OUTPUT
_POSITIV
_NO_SET
_EMPTY


END_STEP
(* @SFCMAXTIME := '' *)
(* @SFCMINTIME := '' *)
(* @SFCCOMMENT := '' *)
ENTRY_ACTION	
_FBD_BODY
_NETWORKS : 1
_NETWORK

_COMMENT
''
_END_COMMENT
_FUNCTIONBLOCK
fbPRG_XYZ_PICKnPLACE_ST
_BOX_EXPR : 2
_OPERAND
_EXPRESSION
_POSITIV
FALSE
_OPERAND
_EXPRESSION
_POSITIV
AxisGroupKin_Inst
_EXPRESSION
_POSITIV
PRG01_XYZ_PICKnPLACE_ST
_OUTPUTS : 1
_OUTPUT
_POSITIV
_NO_SET
_EMPTY

END_ACTION

TRANSITION new Mode or Done   FROM S250_XYZ_PICKnPLACE_ST TO S000_Init:= 
_FBD_BODY
_NETWORKS : 1
_NETWORK

_COMMENT
''
_END_COMMENT
_OPERATOR
_BOX_EXPR : 2
_OPERATOR
_BOX_EXPR : 2
_OPERAND
_EXPRESSION
_POSITIV
gKinExamples_Control[InstanceNumber].ProgramNumber
_OPERAND
_EXPRESSION
_POSITIV
1
_EXPRESSION
_POSITIV
NE
_OPERAND
_EXPRESSION
_POSITIV
fbPRG_XYZ_PICKnPLACE_ST.Done
_EXPRESSION
_POSITIV
OR


END_TRANSITION

END_FUNCTION_BLOCK


(* @NESTEDCOMMENTS := 'Yes' *)
(* @PATH := '\/AxisGroupControl_Kinematics\/Examples' *)
(* @OBJECTFLAGS := '0, 8' *)
(* @SYMFILEFLAGS := '2048' *)
(*##############################################################################################################

	IMPORTANT NOTICE:
 	This example is a special and free service that demonstrates only the basic 
	approach to generating a PLC program as a non-binding sample. 
	SEW is not liable for the contents of the sample program.

	Name:			PRG_XYZ_PICKnPLACE_ST
	Job:			Example program		
					Sequence: XYZ_PICKnPLACE_P2 -> P3 -> P4 -> P3 -> P2 -> P1
					
################################################################################################################*)
FUNCTION_BLOCK  PRG01_XYZ_PICKnPLACE_ST
VAR_INPUT
	Enable : BOOL;
END_VAR
VAR_OUTPUT
	Active : BOOL;
	Done : BOOL;
END_VAR
VAR
	nState : INT := 0;
	fbRtrig : R_TRIG;
	i : INT;
END_VAR
VAR_IN_OUT
	AxisGroupKin_Inst											: ST_AxisGroupKin_Instance;
END_VAR

(* @END_DECLARATION := '0' *)
(* Initialisation at rising edge of VAR_INPUT Enable *)
fbRtrig(CLK:=Enable);
IF fbRtrig.Q THEN
	nState := 0;
	Active := TRUE;
END_IF

(* No execution, if Enable = False *)
IF (Enable = FALSE) THEN
	Done := FALSE;
	RETURN;
END_IF


CASE nState OF
0:	(*Start*)
	IF AxisGroupKin.ConfigDataAvailable THEN
		nState := 5;
	END_IF

5:	(* Up *)
	(* Initialize Kinematic Flags*)
	AxisGroupKin_Inst.In.Cp.Settings.PlusTargetCartABC:=FALSE;
	AxisGroupKin_Inst.In.Cp.Settings.UseMasterPosition:=FALSE;

(* TARGET_CART settings *)
	(* Motion Parameters *)
	AxisGroupKin_Inst.In.Target.Cart.Velocity := CART_VEL100;
	AxisGroupKin_Inst.In.Target.Cart.Acceleration := CART_ACC100;
	AxisGroupKin_Inst.In.Target.Cart.Deceleration := CART_DEC100;
	AxisGroupKin_Inst.In.Target.Cart.Jerk:=CART_Jerk100;
	AxisGroupKin_Inst.In.Target.Synchronization:= KIN_NO_SYNC;
	(* Coordinate System *)
	AxisGroupKin_Inst.In.Target.CoordSys:=KIN_KCS;

	AxisGroupKin_Inst.In.General.Mode := KIN_TARGET_CART;

	AxisGroupKin_Inst.In.Target.Position := XYZ_PICKnPLACE_P2;

	IF (MC_KinInProximity(Threshold := XYZ_PICKnPLACE_BlendingDistance,
			Position := AxisGroupKin_Inst.In.Target.Position,
			CoordSys := AxisGroupKin_Inst.In.Target.CoordSys,
			Dimension := 2#0000_0111, ActPos := AxisGroupKin_Inst.Out.General.Position)) THEN
		nState := 10;
	END_IF
	AxisGroupKin_Inst.In.Simu3D.Ctrl.Pen_TCP_WCS:=TRUE;

10:	(* Side *)
	AxisGroupKin_Inst.In.Target.Position := XYZ_PICKnPLACE_P3;
	IF (MC_KinInProximity(Threshold := XYZ_PICKnPLACE_BlendingDistance,
			Position := AxisGroupKin_Inst.In.Target.Position,
			CoordSys := AxisGroupKin_Inst.In.Target.CoordSys,
			Dimension := 2#0000_0111, ActPos := AxisGroupKin_Inst.Out.General.Position)) THEN
		nState := 20;
	END_IF

20:	(* Down *)
	AxisGroupKin_Inst.In.Target.Position := XYZ_PICKnPLACE_P4;
	IF (MC_KinInProximity(Threshold := 0.0,
			Position := AxisGroupKin_Inst.In.Target.Position,
			CoordSys := AxisGroupKin_Inst.In.Target.CoordSys,
			Dimension := 2#0000_0111, ActPos := AxisGroupKin_Inst.Out.General.Position)
			AND AxisGroupKin_Inst.Out.General.Standstill.ActCoordSys) THEN
		nState :=30;
	END_IF

30:	(* Up *)
	AxisGroupKin_Inst.In.Target.Position := XYZ_PICKnPLACE_P3;
	IF (MC_KinInProximity(Threshold := XYZ_PICKnPLACE_BlendingDistance,
			Position := AxisGroupKin_Inst.In.Target.Position,
			CoordSys := AxisGroupKin_Inst.In.Target.CoordSys,
			Dimension := 2#0000_0111, ActPos := AxisGroupKin_Inst.Out.General.Position)) THEN
		nState := 40;
	END_IF

40:	(* Side *)
	AxisGroupKin_Inst.In.Target.Position := XYZ_PICKnPLACE_P2;
	IF (MC_KinInProximity(Threshold := XYZ_PICKnPLACE_BlendingDistance,
			Position := AxisGroupKin_Inst.In.Target.Position,
			CoordSys := AxisGroupKin_Inst.In.Target.CoordSys,
			Dimension := 2#0000_0111, ActPos := AxisGroupKin_Inst.Out.General.Position)) THEN
		nState := 50;
	END_IF

50:	(* Down *)
	AxisGroupKin_Inst.In.Target.Position := XYZ_PICKnPLACE_P1;
	IF (MC_KinInProximity(Threshold := 0.0,
			Position := AxisGroupKin_Inst.In.Target.Position,
			CoordSys := AxisGroupKin_Inst.In.Target.CoordSys,
			Dimension := 2#0000_0111, ActPos := AxisGroupKin_Inst.Out.General.Position)
			AND AxisGroupKin_Inst.Out.General.Standstill.ActCoordSys) THEN
		AxisGroupKin_Inst.In.Simu3D.Ctrl.Pen_TCP_WCS:=FALSE;
		Done := TRUE;
		Active := FALSE;
	END_IF

ELSE
;

END_CASE
END_FUNCTION_BLOCK


(* @NESTEDCOMMENTS := 'Yes' *)
(* @PATH := '\/AxisGroupControl_Kinematics\/Examples' *)
(* @OBJECTFLAGS := '0, 8' *)
(* @SYMFILEFLAGS := '2048' *)
(*##############################################################################################################

	IMPORTANT NOTICE:
 	This example is a special and free service that demonstrates only the basic 
	approach to generating a PLC program as a non-binding sample. 
	SEW is not liable for the contents of the sample program.

	Name:			PRG_XYZ_PICKnPLACE_SFC
	Job:			Example program		
					Sequence: XYZ_PICKnPLACE_P2 -> P3 -> P4 -> P3 -> P2 -> P1	

################################################################################################################*)
FUNCTION_BLOCK PRG02_XYZ_PICKnPLACE_SFC
VAR_INPUT
	SFCReset:BOOL;
	(*SFCInit:BOOL;*)
	SFCPause:BOOL;

	SFCTipMode:BOOL;
	SFCTip:BOOL;
	SFCEnableLimit:BOOL;
	SFCQuitError:BOOL;
END_VAR
VAR_OUTPUT
	SFCTrans:BOOL;
	SFCError:BOOL;
	SFCErrorStep:STRING;
	SFCErrorPOU:STRING;
	SFCCurrentStep:STRING;
	Done:BOOL;
END_VAR
VAR

END_VAR
VAR_IN_OUT
	AxisGroupKin_Inst											: ST_AxisGroupKin_Instance;
END_VAR

(* @END_DECLARATION := '0' *)

INITIAL_STEP Start:
Done:=FALSE;

END_STEP
(* @SFCMAXTIME := '' *)
(* @SFCMINTIME := '' *)
(* @SFCCOMMENT := '' *)
TRANSITION FROM Start TO Init:= 
AxisGroupKin.ConfigDataAvailable


END_TRANSITION
STEP Init:
(* Initialize Kinematic Flags*)
	AxisGroupKin_Inst.In.Cp.Settings.PlusTargetCartABC:=FALSE;
	AxisGroupKin_Inst.In.Cp.Settings.UseMasterPosition:=FALSE;

(* TARGET_CART settings *)
	(* Motion Parameters *)
	AxisGroupKin_Inst.In.Target.Cart.Velocity := CART_VEL100;
	AxisGroupKin_Inst.In.Target.Cart.Acceleration := CART_ACC100;
	AxisGroupKin_Inst.In.Target.Cart.Deceleration := CART_DEC100;
	AxisGroupKin_Inst.In.Target.Cart.Jerk := CART_Jerk100;
	AxisGroupKin_Inst.In.Target.Synchronization := KIN_NO_SYNC;
	(* Coordinate System *)
	AxisGroupKin_Inst.In.Target.CoordSys := KIN_KCS;

	AxisGroupKin_Inst.In.General.Mode := KIN_TARGET_CART;



END_STEP
(* @SFCMAXTIME := '' *)
(* @SFCMINTIME := '' *)
(* @SFCCOMMENT := '' *)
TRANSITION FROM Init TO S00_TARGET_CART_P2:= 
TRUE


END_TRANSITION
STEP S00_TARGET_CART_P2:
AxisGroupKin_Inst.In.Target.Position := XYZ_PICKnPLACE_P2;

END_STEP
(* @SFCMAXTIME := '' *)
(* @SFCMINTIME := '' *)
(* @SFCCOMMENT := '' *)
TRANSITION Transition  FROM S00_TARGET_CART_P2 TO S10_TARGET_CART_P3:= 
MC_KinInProximity(Threshold := XYZ_PICKnPLACE_BlendingDistance,
			Position := AxisGroupKin_Inst.In.Target.Position,
			CoordSys := AxisGroupKin_Inst.In.Target.CoordSys,
			Dimension := 2#0000_0111, ActPos := AxisGroupKin_Inst.Out.General.Position)

END_TRANSITION
STEP S10_TARGET_CART_P3:
AxisGroupKin_Inst.In.Target.Position := XYZ_PICKnPLACE_P3;

END_STEP
(* @SFCMAXTIME := '' *)
(* @SFCMINTIME := '' *)
(* @SFCCOMMENT := '' *)
TRANSITION Transition  FROM S10_TARGET_CART_P3 TO S20_TARGET_CART_P4:= 
MC_KinInProximity(Threshold := XYZ_PICKnPLACE_BlendingDistance,
			Position := AxisGroupKin_Inst.In.Target.Position,
			CoordSys := AxisGroupKin_Inst.In.Target.CoordSys,
			Dimension := 2#0000_0111, ActPos := AxisGroupKin_Inst.Out.General.Position)

END_TRANSITION
STEP S20_TARGET_CART_P4:
AxisGroupKin_Inst.In.Target.Position := XYZ_PICKnPLACE_P4;

END_STEP
(* @SFCMAXTIME := '' *)
(* @SFCMINTIME := '' *)
(* @SFCCOMMENT := '' *)
TRANSITION Transition  FROM S20_TARGET_CART_P4 TO S30_TARGET_CART_P3:= 
MC_KinInProximity(Threshold := 0.0,
			Position := AxisGroupKin_Inst.In.Target.Position,
			CoordSys := AxisGroupKin_Inst.In.Target.CoordSys,
			Dimension := 2#0000_0111, ActPos := AxisGroupKin_Inst.Out.General.Position)
AND
AxisGroupKin_Inst.Out.General.Standstill.ActCoordSys

END_TRANSITION
STEP S30_TARGET_CART_P3:
AxisGroupKin_Inst.In.Target.Position := XYZ_PICKnPLACE_P3;

END_STEP
(* @SFCMAXTIME := '' *)
(* @SFCMINTIME := '' *)
(* @SFCCOMMENT := '' *)
TRANSITION Transition  FROM S30_TARGET_CART_P3 TO S40_TARGET_CART_P2:= 
MC_KinInProximity(Threshold := XYZ_PICKnPLACE_BlendingDistance,
			Position := AxisGroupKin_Inst.In.Target.Position,
			CoordSys := AxisGroupKin_Inst.In.Target.CoordSys,
			Dimension := 2#0000_0111, ActPos := AxisGroupKin_Inst.Out.General.Position)

END_TRANSITION
STEP S40_TARGET_CART_P2:
AxisGroupKin_Inst.In.Target.Position := XYZ_PICKnPLACE_P2;

END_STEP
(* @SFCMAXTIME := '' *)
(* @SFCMINTIME := '' *)
(* @SFCCOMMENT := '' *)
TRANSITION Transition  FROM S40_TARGET_CART_P2 TO S50_TARGET_CART_P1:= 
MC_KinInProximity(Threshold := XYZ_PICKnPLACE_BlendingDistance,
			Position := AxisGroupKin_Inst.In.Target.Position,
			CoordSys := AxisGroupKin_Inst.In.Target.CoordSys,
			Dimension := 2#0000_0111, ActPos := AxisGroupKin_Inst.Out.General.Position)

END_TRANSITION
STEP S50_TARGET_CART_P1:
AxisGroupKin_Inst.In.Target.Position := XYZ_PICKnPLACE_P1;

END_STEP
(* @SFCMAXTIME := '' *)
(* @SFCMINTIME := '' *)
(* @SFCCOMMENT := '' *)
TRANSITION Transition  FROM S50_TARGET_CART_P1 TO S60_ProgEnd:= 
MC_KinInProximity(Threshold := 0.0,
			Position := AxisGroupKin_Inst.In.Target.Position,
			CoordSys := AxisGroupKin_Inst.In.Target.CoordSys,
			Dimension := 2#0000_0111, ActPos := AxisGroupKin_Inst.Out.General.Position)
AND
AxisGroupKin_Inst.Out.General.Standstill.ActCoordSys

END_TRANSITION
STEP S60_ProgEnd:
Done:=TRUE;

END_STEP
(* @SFCMAXTIME := '' *)
(* @SFCMINTIME := '' *)
(* @SFCCOMMENT := '' *)
TRANSITION FROM S60_ProgEnd TO Init:= 
TRUE


END_TRANSITION

END_FUNCTION_BLOCK


(* @NESTEDCOMMENTS := 'Yes' *)
(* @PATH := '\/AxisGroupControl_Kinematics\/Examples' *)
(* @OBJECTFLAGS := '0, 8' *)
(* @SYMFILEFLAGS := '2048' *)
(*##############################################################################################################

	IMPORTANT NOTICE:
 	This example is a special and free service that demonstrates only the basic 
	approach to generating a PLC program as a non-binding sample. 
	SEW is not liable for the contents of the sample program.

	Name:			PRG_XYZ_TARG_LIN_CIRC_ST
	Job:			Example program			
					Sequence: TARGET_CART to XYZ_TARG_LIN_CIRC_P1 -> LIN_XY to P2 -> CIRC_XZ with R3/A3 -> LIN_3D to P4 -> LIN_XY to P1

################################################################################################################*)
FUNCTION_BLOCK PRG03_XYZ_TARG_LIN_CIRC_ST
VAR_INPUT
	Enable : BOOL;
END_VAR
VAR_OUTPUT
	Active : BOOL;
	Done : BOOL;
END_VAR
VAR
	nState : INT;
	fbRtrig : R_TRIG;
END_VAR
VAR_IN_OUT
	AxisGroupKin_Inst											: ST_AxisGroupKin_Instance;
END_VAR


(* @END_DECLARATION := '0' *)
(* Initialisation at rising edge of VAR_INPUT Enable *)
fbRtrig(CLK:=Enable);
IF fbRtrig.Q THEN
	nState	:= 0;
	Active := TRUE;
END_IF

(* No execution, if Enable = False *)
IF NOT Enable THEN
	Done := FALSE;
	RETURN;
END_IF


CASE nState OF
0:	(*Start*)
	IF AxisGroupKin.ConfigDataAvailable THEN
		nState := 5;
	END_IF
5:	(* TARGET_CART to XYZ_TARG_LIN_CIRC_P1 *)
	(* Initialize Kinematic Flags*)
	AxisGroupKin_Inst.In.Cp.Settings.PlusTargetCartABC:=FALSE;
	AxisGroupKin_Inst.In.Cp.Settings.UseMasterPosition:=FALSE;

(* TARGET_CART settings *)
	(* Motion Parameters *)
	AxisGroupKin_Inst.In.Target.Cart.Acceleration := CART_ACC50;
	AxisGroupKin_Inst.In.Target.Cart.Deceleration := CART_DEC50;
	AxisGroupKin_Inst.In.Target.Cart.Velocity := CART_VEL50;
	AxisGroupKin_Inst.In.Target.Cart.Jerk:=CART_Jerk100;
	AxisGroupKin_Inst.In.Target.Synchronization:= KIN_NO_SYNC;
	(* Coordinate System *)
	AxisGroupKin_Inst.In.Target.CoordSys:=KIN_KCS;

	AxisGroupKin_Inst.In.General.Mode := KIN_TARGET_CART;

	AxisGroupKin_Inst.In.Target.Position := XYZ_TARG_LIN_CIRC_P1;
	IF (MC_KinInProximity(Threshold := 0.0,
			Position := AxisGroupKin_Inst.In.Target.Position,
			CoordSys := AxisGroupKin_Inst.In.Target.CoordSys,
			Dimension := 2#0000_0111, ActPos := AxisGroupKin_Inst.Out.General.Position)
			AND AxisGroupKin_Inst.Out.General.Standstill.ActCoordSys) THEN
		nState := 10;
	END_IF

10:	(* Straight line to XYZ_TARG_LIN_CIRC_P2, as soon as XYZ_TARG_LIN_CIRC_P1 has been reached *)

		AxisGroupKin_Inst.In.General.Mode := KIN_LIN_XY;
		AxisGroupKin_Inst.In.Cp.Segment.Position := XYZ_TARG_LIN_CIRC_P2;
(* CP motion parameters *)
		(* settings for whole path / all segments *)
		AxisGroupKin_Inst.In.Cp.Path.VelocityPercentage:=100;
		AxisGroupKin_Inst.In.Cp.Path.FidelityPercentage :=100;
		(* Settings for the segment, which should be added to the queue *)
		AxisGroupKin_Inst.In.Cp.Segment.Translation.Velocity := 1000;
		AxisGroupKin_Inst.In.Cp.Segment.Translation.Acceleration := 100;
		AxisGroupKin_Inst.In.Cp.Segment.Translation.Deceleration := 100;
		AxisGroupKin_Inst.In.Cp.Segment.Translation.Jerk := 100;
		AxisGroupKin_Inst.In.Cp.Segment.Blending.Distance := 50;
		AxisGroupKin_Inst.In.Cp.Segment.Blending.LimitationPercentage := 50;

		AxisGroupKin_Inst.In.Cp.Segment.ID := AxisGroupKin_Inst.In.Cp.Segment.ID + 1;	(* Change the SegmentID to add the segment to the queue *)

		AxisGroupKin_Inst.In.Simu3D.Ctrl.Pen_TCP_WCS := TRUE;

		nState := 20;

20:	(* A circle section is written into the queue directly after the straight line *)
	IF (AxisGroupKin_Inst.Out.Cp.Queue.LastMappedSegID = AxisGroupKin_Inst.In.Cp.Segment.ID) THEN (* Wait until the segment was added to the queue; this is not required if FB_KinControl is executed in the same task *)
		AxisGroupKin_Inst.In.General.Mode := KIN_CIRC_ZX;
		(* Parameters to define the circle *)
		AxisGroupKin_Inst.In.Cp.Segment.Circ.Mode := KIN_RADIUS_ANGLE;	(* Define the circle with the radius and angle *)
		AxisGroupKin_Inst.In.Cp.Segment.Circ.Direction := KIN_CW;	(* Draw circle ClockWise *)
		AxisGroupKin_Inst.In.Cp.Segment.Circ.Radius := XYZ_TARG_LIN_CIRC_R3;
		AxisGroupKin_Inst.In.Cp.Segment.Circ.Angle := XYZ_TARG_LIN_CIRC_A3;


		AxisGroupKin_Inst.In.Cp.Segment.ID := AxisGroupKin_Inst.In.Cp.Segment.ID + 1;
		nState := 30;
	END_IF

30:	(* A Straight line to XYZ_TARG_LIN_CIRC_P4 is written into the queue directly after the circle section
		-> Blending to the straight line is performed automatically *)
	IF (AxisGroupKin_Inst.Out.Cp.Queue.LastMappedSegID = AxisGroupKin_Inst.In.Cp.Segment.ID) THEN
		AxisGroupKin_Inst.In.General.Mode := KIN_LIN_3D;
		AxisGroupKin_Inst.In.Cp.Segment.Position := XYZ_TARG_LIN_CIRC_P4;


		AxisGroupKin_Inst.In.Cp.Segment.ID := AxisGroupKin_Inst.In.Cp.Segment.ID + 1;
		nState := 40;
	END_IF

40:	(* Straight line to XYZ_TARG_LIN_CIRC_P1 is written into the queue directly after the previous straight line
		-> Blending to the straight line is performed automatically *)
	IF (AxisGroupKin_Inst.Out.Cp.Queue.LastMappedSegID = AxisGroupKin_Inst.In.Cp.Segment.ID) THEN
		AxisGroupKin_Inst.In.General.Mode := KIN_LIN_XY;
		AxisGroupKin_Inst.In.Cp.Segment.Position := XYZ_TARG_LIN_CIRC_P1;


		AxisGroupKin_Inst.In.Cp.Segment.ID := AxisGroupKin_Inst.In.Cp.Segment.ID + 1;
		nState := 50;
	END_IF

50:	(* Program end, as soon as XYZ_TARG_LIN_CIRC_P1 has been reached *)
	IF (AxisGroupKin_Inst.Out.Cp.Path.EndReached)
	AND (AxisGroupKin_Inst.Out.Cp.Queue.LastMappedSegID = AxisGroupKin_Inst.In.Cp.Segment.ID) THEN
		Done := TRUE;
		Active := FALSE;
		AxisGroupKin_Inst.In.Simu3D.Ctrl.Pen_TCP_WCS := FALSE;
	END_IF

ELSE
;

END_CASE
END_FUNCTION_BLOCK


(* @NESTEDCOMMENTS := 'Yes' *)
(* @PATH := '\/AxisGroupControl_Kinematics\/Examples' *)
(* @OBJECTFLAGS := '0, 8' *)
(* @SYMFILEFLAGS := '2048' *)
(*##############################################################################################################

	IMPORTANT NOTICE:
 	This example is a special and free service that demonstrates only the basic 
	approach to generating a PLC program as a non-binding sample. 
	SEW is not liable for the contents of the sample program.

	Name:			PRG_XYZ_TARG_LIN_CIRC_SFC
	Job:			Example program			
					Sequence: TARGET_CART to XYZ_TARG_LIN_CIRC_P1 -> LIN_XY to P2 -> CIRC_XZ with R3/A3 -> LIN_3D to P4 -> LIN_XY to P1

################################################################################################################*)
FUNCTION_BLOCK PRG04_XYZ_TARG_LIN_CIRC_SFC
VAR_INPUT
	SFCReset:BOOL;
	(*SFCInit:BOOL;*)
	SFCPause:BOOL;

	SFCTipMode:BOOL;
	SFCTip:BOOL;
	SFCEnableLimit:BOOL;
	SFCQuitError:BOOL;

END_VAR
VAR_OUTPUT
	SFCTrans:BOOL;
	SFCError:BOOL;
	SFCErrorStep:STRING;
	SFCErrorPOU:STRING;
(*	SFCErrorAnalyzation:STRING;*)
	SFCCurrentStep:STRING;
	Done:BOOL;
END_VAR
VAR

END_VAR
VAR_IN_OUT
	AxisGroupKin_Inst											: ST_AxisGroupKin_Instance;
END_VAR

(* @END_DECLARATION := '0' *)

INITIAL_STEP Start:
Done:=FALSE;

END_STEP
(* @SFCMAXTIME := '' *)
(* @SFCMINTIME := '' *)
(* @SFCCOMMENT := '' *)
TRANSITION FROM Start TO Init:= 
AxisGroupKin.ConfigDataAvailable


END_TRANSITION
STEP Init:
(* Initialize Kinematic Flags*)
	AxisGroupKin_Inst.In.Cp.Settings.PlusTargetCartABC:=FALSE;
	AxisGroupKin_Inst.In.Cp.Settings.UseMasterPosition:=FALSE;

(* TARGET_CART settings *)
	(* Motion Parameters *)
	AxisGroupKin_Inst.In.Target.Cart.Acceleration := CART_ACC50;
	AxisGroupKin_Inst.In.Target.Cart.Deceleration := CART_DEC50;
	AxisGroupKin_Inst.In.Target.Cart.Velocity := CART_VEL50;
	AxisGroupKin_Inst.In.Target.Cart.Jerk:=CART_Jerk100;
	AxisGroupKin_Inst.In.Target.Synchronization:= KIN_NO_SYNC;
	(* Coordinate System *)
	AxisGroupKin_Inst.In.Target.CoordSys:=KIN_KCS;

	AxisGroupKin_Inst.In.General.Mode := KIN_TARGET_CART;



END_STEP
(* @SFCMAXTIME := '' *)
(* @SFCMINTIME := '' *)
(* @SFCCOMMENT := '' *)
TRANSITION FROM Init TO S00_TARGET_CART_P1:= 
TRUE


END_TRANSITION
STEP S00_TARGET_CART_P1:
AxisGroupKin_Inst.In.Target.Position :=  XYZ_TARG_LIN_CIRC_P1;

END_STEP
(* @SFCMAXTIME := '' *)
(* @SFCMINTIME := '' *)
(* @SFCCOMMENT := '' *)
TRANSITION Transition  FROM S00_TARGET_CART_P1 TO S10_LIN_XY_P2:= 
MC_KinInProximity(Threshold := 0.0,
			Position := AxisGroupKin_Inst.In.Target.Position,
			CoordSys := AxisGroupKin_Inst.In.Target.CoordSys,
			Dimension := 2#0000_0111, ActPos := AxisGroupKin_Inst.Out.General.Position)
AND
AxisGroupKin_Inst.Out.General.Standstill.ActCoordSys

END_TRANSITION
STEP S10_LIN_XY_P2:


END_STEP
(* @SFCMAXTIME := '' *)
(* @SFCMINTIME := '' *)
(* @SFCCOMMENT := '' *)
ENTRY_ACTION	
(* Straight line to XYZ_TARG_LIN_CIRC_P2, as soon as XYZ_TARG_LIN_CIRC_P1 has been reached *)

		AxisGroupKin_Inst.In.General.Mode := KIN_LIN_XY;
		AxisGroupKin_Inst.In.Cp.Segment.Position := XYZ_TARG_LIN_CIRC_P2;
(* CP motion parameters *)
		(* settings for whole path / all segments *)
		AxisGroupKin_Inst.In.Cp.Path.VelocityPercentage:=100;
		AxisGroupKin_Inst.In.Cp.Path.FidelityPercentage :=100;
		(* Settings for the segment, which should be added to the queue *)
		AxisGroupKin_Inst.In.Cp.Segment.Translation.Velocity := 1000;
		AxisGroupKin_Inst.In.Cp.Segment.Translation.Acceleration := 100;
		AxisGroupKin_Inst.In.Cp.Segment.Translation.Deceleration := 100;
		AxisGroupKin_Inst.In.Cp.Segment.Translation.Jerk := 100;
		AxisGroupKin_Inst.In.Cp.Segment.Blending.Distance := 50;
		AxisGroupKin_Inst.In.Cp.Segment.Blending.LimitationPercentage := 50;

		AxisGroupKin_Inst.In.Cp.Segment.ID := AxisGroupKin_Inst.In.Cp.Segment.ID + 1;	(* Change the SegmentID to add the segment to the queue *)

		AxisGroupKin_Inst.In.Simu3D.Ctrl.Pen_TCP_WCS := TRUE;

END_ACTION

TRANSITION Transition  FROM S10_LIN_XY_P2 TO S20_CIRC_ZX_Radius:= 
(* Wait until the segment was added to the queue; this is not required if FB_KinControl is executed in the same task *)
AxisGroupKin_Inst.Out.Cp.Queue.LastMappedSegID = AxisGroupKin_Inst.In.Cp.Segment.ID

END_TRANSITION
STEP S20_CIRC_ZX_Radius:


END_STEP
(* @SFCMAXTIME := '' *)
(* @SFCMINTIME := '' *)
(* @SFCCOMMENT := '' *)
ENTRY_ACTION	
AxisGroupKin_Inst.In.General.Mode := KIN_CIRC_ZX;
(* Parameters to define the circle *)
AxisGroupKin_Inst.In.Cp.Segment.Circ.Mode := KIN_RADIUS_ANGLE;	(* Define the circle with the radius and angle *)
AxisGroupKin_Inst.In.Cp.Segment.Circ.Direction := KIN_CW;	(* Draw circle ClockWise *)
AxisGroupKin_Inst.In.Cp.Segment.Circ.Radius := XYZ_TARG_LIN_CIRC_R3;
AxisGroupKin_Inst.In.Cp.Segment.Circ.Angle := XYZ_TARG_LIN_CIRC_A3;


AxisGroupKin_Inst.In.Cp.Segment.ID := AxisGroupKin_Inst.In.Cp.Segment.ID + 1;
END_ACTION

TRANSITION Transition  FROM S20_CIRC_ZX_Radius TO S30_LIN_3D_P4:= 
(* Wait until the segment was added to the queue; this is not required if FB_KinControl is executed in the same task *)
AxisGroupKin_Inst.Out.Cp.Queue.LastMappedSegID = AxisGroupKin_Inst.In.Cp.Segment.ID

END_TRANSITION
STEP S30_LIN_3D_P4:


END_STEP
(* @SFCMAXTIME := '' *)
(* @SFCMINTIME := '' *)
(* @SFCCOMMENT := '' *)
ENTRY_ACTION	
AxisGroupKin_Inst.In.General.Mode := KIN_LIN_3D;
AxisGroupKin_Inst.In.Cp.Segment.Position := XYZ_TARG_LIN_CIRC_P4;


AxisGroupKin_Inst.In.Cp.Segment.ID := AxisGroupKin_Inst.In.Cp.Segment.ID + 1;
END_ACTION

TRANSITION Transition  FROM S30_LIN_3D_P4 TO S40_LIN_XY_P1:= 
(* Wait until the segment was added to the queue; this is not required if FB_KinControl is executed in the same task *)
AxisGroupKin_Inst.Out.Cp.Queue.LastMappedSegID = AxisGroupKin_Inst.In.Cp.Segment.ID

END_TRANSITION
STEP S40_LIN_XY_P1:


END_STEP
(* @SFCMAXTIME := '' *)
(* @SFCMINTIME := '' *)
(* @SFCCOMMENT := '' *)
ENTRY_ACTION	
AxisGroupKin_Inst.In.General.Mode := KIN_LIN_XY;
AxisGroupKin_Inst.In.Cp.Segment.Position := XYZ_TARG_LIN_CIRC_P1;


AxisGroupKin_Inst.In.Cp.Segment.ID := AxisGroupKin_Inst.In.Cp.Segment.ID + 1;
END_ACTION

TRANSITION Transition  FROM S40_LIN_XY_P1 TO S50_ProgEnd:= 
(AxisGroupKin_Inst.Out.Cp.Path.EndReached) AND
(AxisGroupKin_Inst.Out.Cp.Queue.LastMappedSegID = AxisGroupKin_Inst.In.Cp.Segment.ID)

END_TRANSITION
STEP S50_ProgEnd:
Done := TRUE;
AxisGroupKin_Inst.In.Simu3D.Ctrl.Pen_TCP_WCS := FALSE;  (* Process Off *)

END_STEP
(* @SFCMAXTIME := '' *)
(* @SFCMINTIME := '' *)
(* @SFCCOMMENT := '' *)
TRANSITION FROM S50_ProgEnd TO Init:= 
TRUE


END_TRANSITION

END_FUNCTION_BLOCK


(* @NESTEDCOMMENTS := 'Yes' *)
(* @PATH := '\/AxisGroupControl_Kinematics\/Examples' *)
(* @OBJECTFLAGS := '0, 8' *)
(* @SYMFILEFLAGS := '2048' *)
(*##############################################################################################################

	IMPORTANT NOTICE:
 	This example is a special and free service that demonstrates only the basic 
	approach to generating a PLC program as a non-binding sample. 
	SEW is not liable for the contents of the sample program.

	Name:			PRG_XYZ_FillQueue_LIN3D_with_Array_ST
	Job:			Example program			

################################################################################################################*)
FUNCTION_BLOCK PRG05_XYZ_FillQueue_LIN3D_with_Array_ST

VAR_INPUT
	Enable: BOOL;
END_VAR
VAR_OUTPUT
	Active: BOOL;
	Done: BOOL;
END_VAR
VAR
	nState : INT := 0;
	i:INT:=1;
END_VAR
VAR_IN_OUT
	AxisGroupKin_Inst											: ST_AxisGroupKin_Instance;
END_VAR

(* @END_DECLARATION := '0' *)
IF NOT Enable THEN
	Done:=FALSE;
	Active := FALSE;
	i:=1;
	nState:=0;
	RETURN;
END_IF
CASE nState OF
0:	(*Start*)
	IF AxisGroupKin.ConfigDataAvailable THEN
		nState := 5;
	END_IF

5:	(* Initialization and TARGET_CART to last point in queue *)

	(* Initialize kinematics flags*)
	AxisGroupKin_Inst.In.Cp.Settings.PlusTargetCartABC :=FALSE;
	AxisGroupKin_Inst.In.Cp.Settings.UseMasterPosition:=FALSE;

(* CP settings *)
	(* Initialize SegID *)
	AxisGroupKin_Inst.In.Cp.Segment.ID := AxisGroupKin_Inst.Out.Cp.Queue.LastMappedSegID;
	(* Initialize global point array *)
	points[1].x:=10;	points[1].y:=100;	points[1].z:=50;
	points[2].x:=10;	points[2].y:=200;	points[2].z:=100;
	points[3].x:=50;	points[3].y:=300;	points[3].z:=50;
	points[4].x:=100;	points[4].y:=350;	points[4].z:=100;
	points[5].x:=200;	points[5].y:=300;	points[5].z:=50;
	points[6].x:=300;	points[6].y:=200;	points[6].z:=100;
	points[7].x:=300;	points[7].y:=100;	points[7].z:=50;
	points[8].x:=200;	points[8].y:=50;	points[8].z:=100;
	points[9].x:=100;	points[9].y:=10;	points[9].z:=50;
	points[10].x:=50;	points[10].y:=50;	points[10].z:=100;
	(* motion parameters for CP modes *)
	AxisGroupKin_Inst.In.Cp.Segment.Translation.Velocity := 100;
	AxisGroupKin_Inst.In.Cp.Segment.Translation.Acceleration := 100;
	AxisGroupKin_Inst.In.Cp.Segment.Translation.Deceleration := 100;
	AxisGroupKin_Inst.In.Cp.Segment.Translation.Jerk := 100;
	AxisGroupKin_Inst.In.Cp.Segment.Blending.Distance := 30;
	AxisGroupKin_Inst.In.Cp.Segment.Blending.LimitationPercentage := 50;
	AxisGroupKin_Inst.In.Cp.Segment.Mode := KIN_CONTINUOUS_PATH;
	AxisGroupKin_Inst.In.Cp.Path.VelocityPercentage:=100;
	AxisGroupKin_Inst.In.Cp.Path.FidelityPercentage :=100;

(* TARGET_CART settings *)
	(* Set motion parameters for target mode*)
	AxisGroupKin_Inst.In.Target.Cart.Acceleration := CART_ACC50;
	AxisGroupKin_Inst.In.Target.Cart.Deceleration := CART_DEC50;
	AxisGroupKin_Inst.In.Target.Cart.Velocity := CART_VEL50;
	AxisGroupKin_Inst.In.Target.Cart.Jerk:=CART_Jerk100;
	AxisGroupKin_Inst.In.Target.CoordSys := KIN_KCS;
	AxisGroupKin_Inst.In.Target.Synchronization:= KIN_NO_SYNC;
	(* move to last point in array *)
	AxisGroupKin_Inst.In.Target.Position[1] := points[10].x;
	AxisGroupKin_Inst.In.Target.Position[2] := points[10].y;
	AxisGroupKin_Inst.In.Target.Position[3] := points[10].z;

	AxisGroupKin_Inst.In.General.Mode := KIN_TARGET_CART;

	IF (MC_KinInProximity(Threshold := 0.0,
			Position := AxisGroupKin_Inst.In.Target.Position,
			CoordSys := AxisGroupKin_Inst.In.Target.CoordSys,
			Dimension := 2#0000_0111, ActPos := AxisGroupKin_Inst.Out.General.Position)
			AND AxisGroupKin_Inst.Out.General.Standstill.ActCoordSys) THEN
		nState := 10;
	END_IF
10:	(*Fill Queue *)
	IF i <=10 THEN
		AxisGroupKin_Inst.In.Simu3D.Ctrl.Pen_TCP_WCS :=TRUE;
		IF AxisGroupKin_Inst.Out.Cp.Queue.LastMappedSegID = AxisGroupKin_Inst.In.Cp.Segment.ID THEN
			AxisGroupKin_Inst.In.General.Mode := KIN_LIN_3D;
			AxisGroupKin_Inst.In.Cp.Segment.Position[1] := points[i].x;
			AxisGroupKin_Inst.In.Cp.Segment.Position[2] := points[i].y;
			AxisGroupKin_Inst.In.Cp.Segment.Position[3] := points[i].z;
			AxisGroupKin_Inst.In.Cp.Segment.ID := AxisGroupKin_Inst.In.Cp.Segment.ID + 1;
			i:=i+1;
		END_IF
	ELSIF AxisGroupKin_Inst.Out.Cp.Path.EndReached THEN
		Done := TRUE;
		Active := FALSE;
		AxisGroupKin_Inst.In.Simu3D.Ctrl.Pen_TCP_WCS := FALSE;
	END_IF
END_CASE
END_FUNCTION_BLOCK


(* @NESTEDCOMMENTS := 'Yes' *)
(* @PATH := '\/AxisGroupControl_Kinematics\/Examples' *)
(* @OBJECTFLAGS := '0, 8' *)
(* @SYMFILEFLAGS := '2048' *)
(*##############################################################################################################

	IMPORTANT NOTICE:
 	This example is a special and free service that demonstrates only the basic 
	approach to generating a PLC program as a non-binding sample. 
	SEW is not liable for the contents of the sample program.

	Name:			PRG_XYZ_FillQueue_LIN3D_with_Array_SFC
	Job:			Example program		

################################################################################################################*)
FUNCTION_BLOCK PRG06_XYZ_FillQueue_LIN3D_with_Array_SFC
VAR_INPUT
	SFCReset:BOOL;
	(*SFCInit:BOOL;*)
	SFCPause:BOOL;

	SFCTipMode:BOOL;
	SFCTip:BOOL;
	SFCEnableLimit:BOOL;
	SFCQuitError:BOOL;

END_VAR
VAR_OUTPUT
	SFCTrans:BOOL;
	SFCError:BOOL;
	SFCErrorStep:STRING;
	SFCErrorPOU:STRING;
	SFCCurrentStep:STRING;
	Done:BOOL;
END_VAR
VAR
	i:INT;
END_VAR
VAR_IN_OUT
	AxisGroupKin_Inst	: ST_AxisGroupKin_Instance;
END_VAR

(* @END_DECLARATION := '0' *)

INITIAL_STEP Start:
Done:=FALSE;

END_STEP
(* @SFCMAXTIME := '' *)
(* @SFCMINTIME := '' *)
(* @SFCCOMMENT := '' *)
TRANSITION FROM Start TO Init:= 
AxisGroupKin.ConfigDataAvailable


END_TRANSITION
STEP Init:
(* Initialize kinematics flags*)
	AxisGroupKin_Inst.In.Cp.Settings.PlusTargetCartABC :=FALSE;
	AxisGroupKin_Inst.In.Cp.Settings.UseMasterPosition:=FALSE;

(* CP settings *)
	(* Initialize SegID *)
	AxisGroupKin_Inst.In.Cp.Segment.ID := AxisGroupKin_Inst.Out.Cp.Queue.LastMappedSegID;
	(* Initialize global point array *)
	points[1].x:=10;	points[1].y:=100;	points[1].z:=50;
	points[2].x:=10;	points[2].y:=200;	points[2].z:=100;
	points[3].x:=50;	points[3].y:=300;	points[3].z:=50;
	points[4].x:=100;	points[4].y:=350;	points[4].z:=100;
	points[5].x:=200;	points[5].y:=300;	points[5].z:=50;
	points[6].x:=300;	points[6].y:=200;	points[6].z:=100;
	points[7].x:=300;	points[7].y:=100;	points[7].z:=50;
	points[8].x:=200;	points[8].y:=50;	points[8].z:=100;
	points[9].x:=100;	points[9].y:=10;	points[9].z:=50;
	points[10].x:=50;	points[10].y:=50;	points[10].z:=100;
	(* motion parameters for CP modes *)
	AxisGroupKin_Inst.In.Cp.Segment.Translation.Velocity := 100;
	AxisGroupKin_Inst.In.Cp.Segment.Translation.Acceleration := 100;
	AxisGroupKin_Inst.In.Cp.Segment.Translation.Deceleration := 100;
	AxisGroupKin_Inst.In.Cp.Segment.Translation.Jerk := 100;
	AxisGroupKin_Inst.In.Cp.Segment.Blending.Distance := 30;
	AxisGroupKin_Inst.In.Cp.Segment.Blending.LimitationPercentage := 50;
	AxisGroupKin_Inst.In.Cp.Segment.Mode := KIN_CONTINUOUS_PATH;
	AxisGroupKin_Inst.In.Cp.Path.VelocityPercentage:=100;
	AxisGroupKin_Inst.In.Cp.Path.FidelityPercentage :=100;

(* TARGET_CART settings *)
	(* Set motion parameters for target mode*)
	AxisGroupKin_Inst.In.Target.Cart.Acceleration := CART_ACC50;
	AxisGroupKin_Inst.In.Target.Cart.Deceleration := CART_DEC50;
	AxisGroupKin_Inst.In.Target.Cart.Velocity := CART_VEL50;
	AxisGroupKin_Inst.In.Target.Cart.Jerk:=CART_Jerk100;
	AxisGroupKin_Inst.In.Target.CoordSys := KIN_KCS;
	AxisGroupKin_Inst.In.Target.Synchronization:= KIN_NO_SYNC;

	AxisGroupKin_Inst.In.General.Mode := KIN_TARGET_CART;

	i:=1;

END_STEP
(* @SFCMAXTIME := '' *)
(* @SFCMINTIME := '' *)
(* @SFCCOMMENT := '' *)
TRANSITION FROM Init TO S00_TARGET_LAST_POINT_OF_ARRAY:= 
TRUE


END_TRANSITION
STEP S00_TARGET_LAST_POINT_OF_ARRAY:
(* move to last point in array *)
AxisGroupKin_Inst.In.Target.Position[1] := points[10].x;
AxisGroupKin_Inst.In.Target.Position[2] := points[10].y;
AxisGroupKin_Inst.In.Target.Position[3] := points[10].z;

END_STEP
(* @SFCMAXTIME := '' *)
(* @SFCMINTIME := '' *)
(* @SFCCOMMENT := '' *)
TRANSITION Transition  FROM S00_TARGET_LAST_POINT_OF_ARRAY TO S05_Next_Array_Element:= 
MC_KinInProximity(Threshold := 0.0,
			Position := AxisGroupKin_Inst.In.Target.Position,
			CoordSys := AxisGroupKin_Inst.In.Target.CoordSys,
			Dimension := 2#0000_0111, ActPos := AxisGroupKin_Inst.Out.General.Position)

AND
AxisGroupKin_Inst.Out.General.Standstill.ActCoordSys

END_TRANSITION
STEP S05_Next_Array_Element:


END_STEP
(* @SFCMAXTIME := '' *)
(* @SFCMINTIME := '' *)
(* @SFCCOMMENT := '' *)
TRANSITION FROM S05_Next_Array_Element TO S10_Fill_Queue:= 
TRUE


END_TRANSITION
STEP S10_Fill_Queue:


END_STEP
(* @SFCMAXTIME := '' *)
(* @SFCMINTIME := '' *)
(* @SFCCOMMENT := '' *)
ENTRY_ACTION	
AxisGroupKin_Inst.In.General.Mode			:= KIN_LIN_3D;
AxisGroupKin_Inst.In.Cp.Segment.Position[1]	:= points[i].x;
AxisGroupKin_Inst.In.Cp.Segment.Position[2] 	:= points[i].y;
AxisGroupKin_Inst.In.Cp.Segment.Position[3] 	:= points[i].z;
AxisGroupKin_Inst.In.Cp.Segment.ID 		:= AxisGroupKin_Inst.In.Cp.Segment.ID + 1;

i:=i+1;
END_ACTION

TRANSITION Transition  FROM S10_Fill_Queue TO S20_Wait_for_Path_end:= 
(AxisGroupKin_Inst.Out.Cp.Queue.LastMappedSegID= AxisGroupKin_Inst.In.Cp.Segment.ID) AND (i >10)

END_TRANSITION
TRANSITION Transition  FROM S10_Fill_Queue TO S05_Next_Array_Element:= 
AxisGroupKin_Inst.Out.Cp.Queue.LastMappedSegID = AxisGroupKin_Inst.In.Cp.Segment.ID

END_TRANSITION
STEP S20_Wait_for_Path_end:


END_STEP
(* @SFCMAXTIME := '' *)
(* @SFCMINTIME := '' *)
(* @SFCCOMMENT := '' *)
TRANSITION Transition  FROM S20_Wait_for_Path_end TO S30_ProgEnd:= 
AxisGroupKin_Inst.Out.Cp.Path.EndReached

END_TRANSITION
STEP S30_ProgEnd:
Done:=TRUE;

END_STEP
(* @SFCMAXTIME := '' *)
(* @SFCMINTIME := '' *)
(* @SFCCOMMENT := '' *)
TRANSITION FROM S30_ProgEnd TO Init:= 
TRUE


END_TRANSITION

END_FUNCTION_BLOCK


(* @NESTEDCOMMENTS := 'Yes' *)
(* @PATH := '\/AxisGroupControl_Kinematics\/Examples' *)
(* @OBJECTFLAGS := '0, 8' *)
(* @SYMFILEFLAGS := '2048' *)
(*##############################################################################################################

	IMPORTANT NOTICE:
 	This example is a special and free service that demonstrates only the basic 
	approach to generating a PLC program as a non-binding sample. 
	SEW is not liable for the contents of the sample program.

	Name:			PRG_XYZ_USER_ST
	Job:			Example program
					Simple program, in which you can implement your own sample sequence.			

################################################################################################################*)
FUNCTION_BLOCK PRG07_XYZ_USER_ST
VAR_INPUT
	Enable : BOOL;
END_VAR
VAR_OUTPUT
	Active : BOOL;
	Done : BOOL;
END_VAR
VAR
	nState : INT;
	fbRtrig : R_TRIG;
END_VAR
VAR_IN_OUT
	AxisGroupKin_Inst											: ST_AxisGroupKin_Instance;
END_VAR


(* @END_DECLARATION := '0' *)
(* Initialisation at rising edge of VAR_INPUT Enable *)
fbRtrig(CLK:=Enable);
IF fbRtrig.Q THEN
	nState	:= 0;
	Active := TRUE;
END_IF

(* No execution, if Enable = False *)
IF NOT Enable THEN
	Done := FALSE;
	RETURN;
END_IF

CASE nState OF
0:	(*Start*)
	IF AxisGroupKin.ConfigDataAvailable THEN
		nState := 5;
	END_IF
5:	(* TARGET_CART to XYZ_USER_P1 *)
	(* Initialize Kinematic Flags*)
	AxisGroupKin_Inst.In.Cp.Settings.PlusTargetCartABC:=FALSE;
	AxisGroupKin_Inst.In.Cp.Settings.UseMasterPosition:=FALSE;

(* TARGET_CART settings *)
	(* Motion Parameters *)
	AxisGroupKin_Inst.In.Target.Cart.Velocity := CART_VEL50;
	AxisGroupKin_Inst.In.Target.Cart.Acceleration := CART_ACC50;
	AxisGroupKin_Inst.In.Target.Cart.Deceleration := CART_DEC50;
	AxisGroupKin_Inst.In.Target.Cart.Jerk:=CART_Jerk100;
	AxisGroupKin_Inst.In.Target.Synchronization:= KIN_NO_SYNC;
	(* Coordinate System *)
	AxisGroupKin_Inst.In.Target.CoordSys:=KIN_KCS;

	AxisGroupKin_Inst.In.General.Mode := KIN_TARGET_CART;

	AxisGroupKin_Inst.In.Simu3D.Ctrl.Pen_TCP_WCS := TRUE;  (* Process On *)

	AxisGroupKin_Inst.In.Target.Position := XYZ_USER_P1;
	IF (MC_KinInProximity(Threshold := 0.0,
			Position := AxisGroupKin_Inst.In.Target.Position,
			CoordSys := AxisGroupKin_Inst.In.Target.CoordSys,
			Dimension := 2#0000_0111, ActPos := AxisGroupKin_Inst.Out.General.Position)
			AND AxisGroupKin_Inst.Out.General.Standstill.ActCoordSys) THEN
		nState := 10;
	END_IF

10:	(* TARGET_CART to XYZ_USER_P2 *)
	AxisGroupKin_Inst.In.Target.Position := XYZ_USER_P2;
	IF (MC_KinInProximity(Threshold := 0.0,
			Position := AxisGroupKin_Inst.In.Target.Position,
			CoordSys := AxisGroupKin_Inst.In.Target.CoordSys,
			Dimension := 2#0000_0111, ActPos := AxisGroupKin_Inst.Out.General.Position)
			AND AxisGroupKin_Inst.Out.General.Standstill.ActCoordSys) THEN
		Done := TRUE;
		Active := FALSE;
		AxisGroupKin_Inst.In.Simu3D.Ctrl.Pen_TCP_WCS := FALSE;  (* Process Off *)
	END_IF

ELSE
;

END_CASE
END_FUNCTION_BLOCK


(* @NESTEDCOMMENTS := 'Yes' *)
(* @PATH := '\/AxisGroupControl_Kinematics\/Examples' *)
(* @OBJECTFLAGS := '0, 8' *)
(* @SYMFILEFLAGS := '2048' *)
(*##############################################################################################################

	IMPORTANT NOTICE:
 	This example is a special and free service that demonstrates only the basic 
	approach to generating a PLC program as a non-binding sample. 
	SEW is not liable for the contents of the sample program.

	Name:			PRG_XYZ_USER_SFC
	Job:			Example program
					Simple program, in which you can implement your own sample sequence.				

################################################################################################################*)
FUNCTION_BLOCK PRG08_XYZ_USER_SFC
VAR_INPUT
	SFCReset:BOOL;
	(*SFCInit:BOOL;*)
	SFCPause:BOOL;

	SFCTipMode:BOOL;
	SFCTip:BOOL;
	SFCEnableLimit:BOOL;
	SFCQuitError:BOOL;

END_VAR
VAR_OUTPUT
	SFCTrans:BOOL;
	SFCError:BOOL;
	SFCErrorStep:STRING;
	SFCErrorPOU:STRING;
(*	SFCErrorAnalyzation:STRING;*)
	SFCCurrentStep:STRING;
	Done:BOOL;
END_VAR
VAR

END_VAR
VAR_IN_OUT
	AxisGroupKin_Inst											: ST_AxisGroupKin_Instance;
END_VAR

(* @END_DECLARATION := '0' *)

INITIAL_STEP Start:
Done:=FALSE;

END_STEP
(* @SFCMAXTIME := '' *)
(* @SFCMINTIME := '' *)
(* @SFCCOMMENT := '' *)
TRANSITION FROM Start TO Init:= 
AxisGroupKin.ConfigDataAvailable


END_TRANSITION
STEP Init:
(* Initialize Kinematic Flags*)
AxisGroupKin_Inst.In.Cp.Settings.PlusTargetCartABC:=FALSE;
AxisGroupKin_Inst.In.Cp.Settings.UseMasterPosition:=FALSE;

(* TARGET_CART settings *)
	(* Motion Parameters *)
	AxisGroupKin_Inst.In.Target.Cart.Velocity := CART_VEL50;
	AxisGroupKin_Inst.In.Target.Cart.Acceleration := CART_ACC50;
	AxisGroupKin_Inst.In.Target.Cart.Deceleration := CART_DEC50;
	AxisGroupKin_Inst.In.Target.Cart.Jerk:=CART_Jerk100;
	AxisGroupKin_Inst.In.Target.Synchronization:= KIN_NO_SYNC;
	(* Coordinate System *)
	AxisGroupKin_Inst.In.Target.CoordSys:=KIN_KCS;

AxisGroupKin_Inst.In.General.Mode := KIN_TARGET_CART;

AxisGroupKin_Inst.In.Simu3D.Ctrl.Pen_TCP_WCS := TRUE;  (* Process On *)



END_STEP
(* @SFCMAXTIME := '' *)
(* @SFCMINTIME := '' *)
(* @SFCCOMMENT := '' *)
TRANSITION FROM Init TO S00_TARGET_CART_P1:= 
TRUE


END_TRANSITION
STEP S00_TARGET_CART_P1:
AxisGroupKin_Inst.In.Target.Position := XYZ_USER_P1;

END_STEP
(* @SFCMAXTIME := '' *)
(* @SFCMINTIME := '' *)
(* @SFCCOMMENT := '' *)
TRANSITION Transition  FROM S00_TARGET_CART_P1 TO S10_TARGET_CART_P2:= 
MC_KinInProximity(Threshold := 0.0,
			Position := AxisGroupKin_Inst.In.Target.Position,
			CoordSys := AxisGroupKin_Inst.In.Target.CoordSys,
			Dimension := 2#0000_0111, ActPos := AxisGroupKin_Inst.Out.General.Position)
AND
AxisGroupKin_Inst.Out.General.Standstill.ActCoordSys

END_TRANSITION
STEP S10_TARGET_CART_P2:
AxisGroupKin_Inst.In.Target.Position := XYZ_USER_P2;

END_STEP
(* @SFCMAXTIME := '' *)
(* @SFCMINTIME := '' *)
(* @SFCCOMMENT := '' *)
TRANSITION Transition  FROM S10_TARGET_CART_P2 TO S60_ProgEnd:= 
MC_KinInProximity(Threshold := 0.0,
			Position := AxisGroupKin_Inst.In.Target.Position,
			CoordSys := AxisGroupKin_Inst.In.Target.CoordSys,
			Dimension := 2#0000_0111, ActPos := AxisGroupKin_Inst.Out.General.Position)
AND
AxisGroupKin_Inst.Out.General.Standstill.ActCoordSys

END_TRANSITION
STEP S60_ProgEnd:
Done := TRUE;
AxisGroupKin_Inst.In.Simu3D.Ctrl.Pen_TCP_WCS := FALSE;  (* Process Off *)

END_STEP
(* @SFCMAXTIME := '' *)
(* @SFCMINTIME := '' *)
(* @SFCCOMMENT := '' *)
TRANSITION FROM S60_ProgEnd TO Init:= 
TRUE


END_TRANSITION

END_FUNCTION_BLOCK


(* @NESTEDCOMMENTS := 'Yes' *)
(* @PATH := '\/PRG_Kinematics' *)
(* @OBJECTFLAGS := '0, 8' *)
(* @SYMFILEFLAGS := '2048' *)
PROGRAM PRG_TaskMain_Kinematics
VAR
	fbUser_Kinematics_Examples : ARRAY[1..KIN_AXISGROUPKIN_MAX_NUMBER_OF_KINEMATICS_INSTANCES] OF FB_User_Kinematics_Examples;
	i : INT;
END_VAR
(* @END_DECLARATION := '0' *)
(*#######################################################################################

	PRG_TaskMain_Kinematics

	ToDo: Call this program in the task configuration after PRG_TaskMain();

#########################################################################################*)

(* Examples for common motion sequences *)
FOR i := 1 TO KIN_AXISGROUPKIN_MAX_NUMBER_OF_KINEMATICS_INSTANCES DO
	fbUser_Kinematics_Examples[i](AxisGroupKin_Inst := AxisGroupKin.Inst[i]);
END_FOR

(* Do not remove! *)
AxisGroupControl_Configuration_Kinematics(Enable := TRUE);

(* Do not remove! *)
AxisGroupControl_Main_Kinematics(Enable := TRUE);


END_PROGRAM


(* @NESTEDCOMMENTS := 'Yes' *)
(* @PATH := '\/PRG_Kinematics' *)
(* @OBJECTFLAGS := '0, 8' *)
(* @SYMFILEFLAGS := '2048' *)
PROGRAM PRG_TaskPriority_Kinematics
VAR
END_VAR
(* @END_DECLARATION := '0' *)
(*#######################################################################################

	PRG_TaskPriority_Kinematics

	ToDo: Call this program in the task configuration after PRG_TaskPriority();

########################################################################################*)

(* Do not remove! *)
AxisGroupControl_Priority_Kinematics();
END_PROGRAM

(* @NESTEDCOMMENTS := 'Yes' *)
(* @PATH := '\/AxisGroupControl_Kinematics\/Examples' *)
(* @OBJECTFLAGS := '0, 8' *)
TYPE ENUM_AxisIndex :(
	A1:=1,
	A2:=2,
	A3:=3,
	A4:=4,
	A5:=5,
	A6:=6,
	A7:=7,
	A8:=8
);
END_TYPE

(* @END_DECLARATION := '0' *)

(* @NESTEDCOMMENTS := 'Yes' *)
(* @PATH := '\/AxisGroupControl_Kinematics\/Examples' *)
(* @OBJECTFLAGS := '0, 8' *)
TYPE ENUM_CartIndex :(
	X:=1,
	Y:=2,
	Z:=3,
	A:=4,
	B:=5,
	C:=6


);
END_TYPE

(* @END_DECLARATION := '0' *)

(* @NESTEDCOMMENTS := 'Yes' *)
(* @PATH := '\/AxisGroupControl_Kinematics\/Examples' *)
(* @OBJECTFLAGS := '0, 8' *)
TYPE ST_AxisGroupKin_Point :
STRUCT
	x: LREAL;
	y: LREAL;
	z: LREAL;
	A: LREAL;
	B: LREAL;
	C: LREAL;
END_STRUCT
END_TYPE
(* @END_DECLARATION := '0' *)

(* @NESTEDCOMMENTS := 'Yes' *)
(* @PATH := '\/AxisGroupControl_Kinematics\/Examples' *)
(* @OBJECTFLAGS := '0, 8' *)
TYPE ST_KinExamples_ControlVariables :
STRUCT
	EnableExamples		: BOOL;

	ProgramNumber 		: DINT := 1;
	ErrorReset 			: BOOL;

	Kin 					: ST_KinExamples_ControlVariables_Kin;
	Inverter				: ST_KinExamples_ControlVariables_Inverter;


END_STRUCT
END_TYPE
(* @END_DECLARATION := '0' *)

(* @NESTEDCOMMENTS := 'Yes' *)
(* @PATH := '\/AxisGroupControl_Kinematics\/Examples' *)
(* @OBJECTFLAGS := '0, 8' *)
TYPE ST_KinExamples_ControlVariables_Inverter :
STRUCT

	Enable_Stop_AllAxis			: BOOL;
	Enable_RapidStop_AllAxis	: BOOL;
	Inhibit_AllAxis 					: BOOL;

END_STRUCT
END_TYPE
(* @END_DECLARATION := '0' *)

(* @NESTEDCOMMENTS := 'Yes' *)
(* @PATH := '\/AxisGroupControl_Kinematics\/Examples' *)
(* @OBJECTFLAGS := '0, 8' *)
TYPE ST_KinExamples_ControlVariables_Kin :
STRUCT

	FeedEnable 			: BOOL;
	RapidStop 			: BOOL;
	OverridePercentage 	: INT := 10;

END_STRUCT
END_TYPE
(* @END_DECLARATION := '0' *)

(* @NESTEDCOMMENTS := 'Yes' *)
(* @PATH := '\/AxisGroupControl_Kinematics\/Examples' *)
(* @OBJECTFLAGS := '0, 8' *)
TYPE ST_KinExamples_SequenceType :
STRUCT
	Reset: BOOL;						(*Die Variable verhält sich ähnlich wie SFCInit. Im Unterschied zu dieser wird allerdings nach der Initialisierungder Init-Schritt weiter abgearbeitet.
										So könnte beispielsweise im Init-Schritt das Flag SFCReset gleich wieder auf FALSE gesetzt werden.*)
	Init: BOOL;							(*Wenn die Variable TRUE ist, wird die Ablaufsprache auf den Init-Schritt zurückgesetzt.
										Die anderen AS-Flags werden ebenfalls zurückgesetzt (Initialisierung). 
										Solange die Variable TRUE ist, bleibt der Init-Schritt gesetzt (aktiv), wird aber nicht ausgeführt.
										Erst wenn SFCInit wieder auf FALSE gesetzt wird, wird der Baustein normal weiterbearbeitet.*)
	EnableLimit: BOOL;				(*Wenn die Variable TRUE ist, werden Zeitüberschreitungen bei den Schritten in SFCError registriert.
										Ansonsten werden Zeitüberschreitungen ignoriert.
										Das Flag kann beispielsweise bei Inbetriebnahme oder Handbetrieb nützlich sein.*)
	QuitError: BOOL;					(*Solange die Variable TRUE ist, wird die Abarbeitung des AS-Diagramms angehalten.
										Eine in der Variablen SFCError registrierte Zeitüberschreitung wird dabei zurückgesetzt. 
										Wenn die Variable wieder auf FALSE gesetzt wird, werden alle bisherigen Zeiten in den aktiven Schritten zurückgesetzt.
										Voraussetzung dafür ist die Deklaration der Variablen SFCError, die die Zeitüberschreitung registriert.*)
	CurrentStep: STRING;			(*In dieser Variablen wird der Name des momentan akitven Schritts gespeichert, unabhängig von der Zeitüberwachung.
										Bei einer Paralellverzweigung wird der Name des Schritts im äußersten rechten Zweig gespeichert*)
	Error: BOOL;						(*Diese Variable wird TRUE, wenn in einem AS-Diagramm eine Zeitüberschreitung aufgetreten ist.
										Wenn nach der ersten Zeitüberschreitung eine weitere auftritt, wird diese nicht mehr registriert, 
										es sei denn, die Variable SFCError wurde vorher wieder zurückgesetzt. 
										Die Deklaration von SFCError ist Voraussetzung für das Funktionieren der anderen Flag-Variablen,
										die zur Kontrolle des zeitlichen Ablaufs dienen (SFCErrorStep, SFCErrorPOU, SFCQuitError, SFCErrorAnalyzationTable.*)
	ErrorStep: STRING; 				(*Wenn in SFCError eine Zeitüberschreitung im AS-Diagramm registriert wird, speichert die Variable den Namen des Schritts,
										der die Zeitüberschreitung verursacht hat.
										Voraussetzung dafür ist die Deklaration der Variablen SFCError, die die Zeitüberschreitung registriert. *)
	Done: BOOL;
END_STRUCT
END_TYPE
(* @END_DECLARATION := '0' *)

(* @NESTEDCOMMENTS := 'Yes' *)
(* @GLOBAL_VARIABLE_LIST := 'GlobalVar_AxisGroupControl_Kinematics_Examples' *)
(* @PATH := '\/AxisGroupControl_Kinematics\/Examples' *)
(* @OBJECTFLAGS := '0, 8' *)
(* @SYMFILEFLAGS := '2048' *)
VAR_GLOBAL
	(* !!! Do not remove '{flag extrasymbolexport on}'. Otherwise the Kinematics Monitor will not work anymore. *)
	{flag extrasymbolexport on}
	gKinExamples_Control	: ARRAY[1..KIN_AXISGROUPKIN_MAX_NUMBER_OF_KINEMATICS_INSTANCES] OF ST_KinExamples_ControlVariables;
	{flag off}

	gsSeqMode				: ARRAY[1..KIN_AXISGROUPKIN_MAX_NUMBER_OF_KINEMATICS_INSTANCES] OF ST_KinExamples_SequenceType;

	CART_VEL1:ARRAY[1..6] OF LREAL := 1,1,1,1,1,1;  (* VEL 1 [user unit / s] *)
	CART_ACC1:ARRAY[1..6] OF LREAL := 1,1,1,1,1,1;  (*ACC 1 [user unit / (s * s)] *)
	CART_DEC1:ARRAY[1..6] OF LREAL := 1,1,1,1,1,1;  (* DEC 1 [user unit / (s * s)]  *)

	CART_VEL10:ARRAY[1..6] OF LREAL := 10,10,10,10,10,10;  (* VEL 10 [user unit / s] *)
	CART_ACC10:ARRAY[1..6] OF LREAL := 10,10,10,10,10,10;  (*ACC 10 [user unit / (s * s)] *)
	CART_DEC10:ARRAY[1..6] OF LREAL := 10,10,10,10,10,10;  (* DEC 10 [user unit / (s * s)]  *)

	CART_VEL20:ARRAY[1..6] OF LREAL := 20,20,20,20,20,20;  (* VEL 20 [user unit / s] *)
	CART_ACC20:ARRAY[1..6] OF LREAL := 20,20,20,20,20,20;  (*ACC 20 [user unit / (s * s)] *)
	CART_DEC20:ARRAY[1..6] OF LREAL := 20,20,20,20,20,20;  (* DEC 20 [user unit / (s * s)]  *)

	CART_VEL50:ARRAY[1..6] OF LREAL := 50,50,50,50,50,50;  (* VEL 50 [user unit / s] *)
	CART_ACC50:ARRAY[1..6] OF LREAL := 50,50,50,50,50,50;  (*ACC 50 [user unit / (s * s)] *)
	CART_DEC50:ARRAY[1..6] OF LREAL := 50,50,50,50,50,50;  (* DEC 50 [user unit / (s * s)]  *)

	CART_VEL100:ARRAY[1..6] OF LREAL := 100,100,100,100,100,100;  (* VEL 100 [user unit / s] *)
	CART_ACC100:ARRAY[1..6] OF LREAL := 100,100,100,100,100,100;  (*ACC 100 [user unit / (s * s)] *)
	CART_DEC100:ARRAY[1..6] OF LREAL := 100,100,100,100,100,100;  (* DEC 100 [user unit / (s * s)]  *)

	CART_VEL200:ARRAY[1..6] OF LREAL := 200,200,200,200,200,200;  (* VEL 200 [user unit / s] *)
	CART_ACC200:ARRAY[1..6] OF LREAL := 200,200,200,200,200,200;  (*ACC 200 [user unit / (s * s)] *)
	CART_DEC200:ARRAY[1..6] OF LREAL := 200,200,200,200,200,200;  (* DEC 200 [user unit / (s * s)]  *)

	CART_VEL1000:ARRAY[1..6] OF LREAL := 1000,1000,1000,1000,1000,1000;  (* VEL 1000 [user unit / s] *)
	CART_ACC1000:ARRAY[1..6] OF LREAL := 1000,1000,1000,1000,1000,1000;  (*ACC 1000 [user unit / (s * s)] *)
	CART_DEC1000:ARRAY[1..6] OF LREAL := 1000,1000,1000,1000,1000,1000;  (* DEC 1000 [user unit / (s * s)]  *)

	CART_JERK100:ARRAY[1..6] OF LREAL := 100,100,100,100,100,100;  (* JERK  [ms] *)

	AXIS_VEL100:ARRAY[1..8] OF LREAL := 100,100,100,100,100,100,100,100;  (* VEL 100 [user unit / s] *)
	AXIS_ACC100:ARRAY[1..8] OF LREAL := 100,100,100,100,100,100,100,100;  (*ACC 100 [user unit / (s * s)] *)
	AXIS_DEC100:ARRAY[1..8] OF LREAL := 100,100,100,100,100,100,100,100;  (* DEC 100 [user unit / (s * s)]  *)
	AXIS_JERK100:ARRAY[1..8] OF LREAL := 100,100,100,100,100,100,100,100;  (* JERK  [ms] *)

	KIN_NO_SYNC: ARRAY[0..8]OF BOOL := FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE;

(* PRG_XYZ_FillQueue_LIN3D_with_Array *)
	points: ARRAY[1..10] OF ST_AxisGroupKin_Point;
(* PRG_XYZ_USER poses and parameters *)
	XYZ_USER_P1 : ARRAY[1..8] OF LREAL := 10,10,0;
	XYZ_USER_P2 : ARRAY[1..8] OF LREAL := 200,200,200;
(* PRG_XYZ_PICKnPLACE poses and parameters *)
	XYZ_PICKnPLACE_P1 : ARRAY[1..8] OF LREAL := 10,0,0;
	XYZ_PICKnPLACE_P2 : ARRAY[1..8] OF LREAL := 10,0,200;
	XYZ_PICKnPLACE_P3 : ARRAY[1..8] OF LREAL := 300,0,200;
	XYZ_PICKnPLACE_P4 : ARRAY[1..8] OF LREAL := 300,0,0;
	XYZ_PICKnPLACE_BlendingDistance : LREAL := 50;
(* PRG_XYZ_LIN_CIRC_LIN poses and parameters *)
	XYZ_TARG_LIN_CIRC_P1 : ARRAY[1..8] OF LREAL := 10,10,0;
	XYZ_TARG_LIN_CIRC_P2 : ARRAY[1..8] OF LREAL := 100,10,0;
	XYZ_TARG_LIN_CIRC_R3 : LREAL := 50;
	XYZ_TARG_LIN_CIRC_A3 : LREAL := 180;
	XYZ_TARG_LIN_CIRC_P4 : ARRAY[1..8] OF LREAL := 10,200,0;

END_VAR
(* @OBJECT_END := 'GlobalVar_AxisGroupControl_Kinematics_Examples' *)
(* @CONNECTIONS := GlobalVar_AxisGroupControl_Kinematics_Examples
FILENAME : ''
FILETIME : 0
EXPORT : 0
NUMOFCONNECTIONS : 0
*)

(* @NESTEDCOMMENTS := 'Yes' *)
(* @GLOBAL_VARIABLE_LIST := 'GlobalVar_AxisGroupControl_Kinematics' *)
(* @PATH := '\/AxisGroupControl_Kinematics' *)
(* @OBJECTFLAGS := '0, 8' *)
(* @SYMFILEFLAGS := '2048' *)
VAR_GLOBAL
	{flag extrasymbolexport on}
	AxisGroupKin 		: ST_AxisGroupKin;
	{flag off}
END_VAR

(* @OBJECT_END := 'GlobalVar_AxisGroupControl_Kinematics' *)
(* @CONNECTIONS := GlobalVar_AxisGroupControl_Kinematics
FILENAME : ''
FILETIME : 0
EXPORT : 0
NUMOFCONNECTIONS : 0
*)

(* @NESTEDCOMMENTS := 'Yes' *)
(* @GLOBAL_VARIABLE_LIST := 'Version_AxisGroupControl_Kinematics' *)
(* @PATH := '\/AxisGroupControl_Kinematics' *)
(* @OBJECTFLAGS := '0, 8' *)
(* @SYMFILEFLAGS := '2048' *)
VAR_GLOBAL
	VERSION_AXISGROUPCONTROL_KINEMATICS : DWORD := 180;
	RELEASE_AXISGROUPCONTROL_KINEMATICS : DWORD := 100;
END_VAR

(* @OBJECT_END := 'Version_AxisGroupControl_Kinematics' *)
(* @CONNECTIONS := Version_AxisGroupControl_Kinematics
FILENAME : ''
FILETIME : 0
EXPORT : 0
NUMOFCONNECTIONS : 0
*)


LIBRARY
03_ApplicationModules\MPLCAxisGroupControl_Kinematics.lib 30.1.17 00:00:00
(* @LIBRARYSYMFILEINFO := '0' *)
NumOfPOUs: 9
AxisControl_Main_Kinematics: 2048
AxisGroupControl_Configuration_Kinematics: 2048
AxisGroupControl_Main_Kinematics: 2048
AxisGroupControl_Priority_Kinematics: 2048
AxisGroupKin_MonitorCpQueue: 2048
F_GetParamValueV2_UDINT: 2048
FB_ReadKin_ApplicationSettings: 2048
MC_Enter_Message_Buffer_AxisGroupControlKin: 2048
MC_Enter_Notice_AxisGroupControlKin: 2048
NumOfGVLs: 2
GlobalVar_MPLCAxisGroupControl_Kinematics: 2048
Version_MPLCAxisGroupControl_Kinematics: 2048
END_LIBRARY

LIBRARY
03_ApplicationModules\MPLCAxisGroupControl_Kinematics_Internal_Inst1.lib 30.1.17 00:00:00
(* @LIBRARYSYMFILEINFO := '0' *)
NumOfPOUs: 0
NumOfGVLs: 1
GlobalVar_MPLCAxisGroupControl_Kinematics_Internal_Inst1: 2048
END_LIBRARY

LIBRARY
04_InterpolatedMotion\MPLCKinematics.lib 30.1.17 00:00:00
(* @LIBRARYSYMFILEINFO := '0' *)
NumOfPOUs: 8
MC_KinCoordSysMeasurement: 2048
MC_KinEncoderDataProcessing: 2048
MC_KinInProximity: 2048
MC_KinMeasurement_QUADROPOD_LLLL_XYZ_M10: 2048
MC_KinMonitorCpQueueSegment: 2048
MC_KinProfGen: 2048
MC_KinWcsPcs1Assignment: 2048
MC_KinWcsPcs2Assignment: 2048
NumOfGVLs: 2
GlobalVar_Kinematics: 2048
Version_MPLCKinematics: 2048
END_LIBRARY

LIBRARY
04_InterpolatedMotion\MPLCKinematics_UserKin.lib 30.1.17 00:00:00
(* @LIBRARYSYMFILEINFO := '0' *)
NumOfPOUs: 9
MC_KinAxisCouplingUser: 2048
MC_KinAxisDecouplingUser: 2048
MC_KinBijectionConfigUser: 2048
MC_KinBijectionDirectUser: 2048
MC_KinBijectionInverseUser: 2048
MC_KinCheckConfigWithoutParValueUser: 2048
MC_KinCheckParValueUser: 2048
MC_KinDirectUser: 2048
MC_KinInverseUser: 2048
NumOfGVLs: 2
GlobalVar_Kinematics_UserKin: 2048
Version_MPLCKinematics_UserKin: 2048
END_LIBRARY

LIBRARY
04_InterpolatedMotion\MPLCKinematics_UserLookAhead.lib 30.1.17 00:00:00
(* @LIBRARYSYMFILEINFO := '0' *)
NumOfPOUs: 1
MC_KinLookAheadUser: 2048
NumOfGVLs: 0
END_LIBRARY

LIBRARY
04_InterpolatedMotion\MPLCSimu3D.lib 30.1.17 00:00:00
(* @LIBRARYSYMFILEINFO := '0' *)
NumOfPOUs: 30
FB_BuildCSharpHeader_3DText: 2048
FB_BuildCSharpHeader_CoordSys: 2048
FB_BuildCSharpHeader_Kinematics: 2048
FB_GetRemoteIPViaBroadcast: 2048
FB_Simu3D_Clear_Pen: 2048
FB_Simu3D_DataExchange_3DText: 2048
FB_Simu3D_DataExchange_CoordSys: 2048
FB_Simu3D_DataExchange_CoordSys.BuildTelegramDescription_CoordSys: 2048
FB_Simu3D_DataExchange_Kinematics: 2048
FB_Simu3D_DataExchange_Kinematics.BuildTelegramDescription_Kinematics: 2048
FB_Simu3D_OpenSimFile_3DText: 2048
FB_Simu3D_OpenSimFile_CoordSys: 2048
FB_Simu3D_OpenSimFile_Kinematics: 2048
FB_Simu3D_ParaToCSharp: 2048
FB_Simu3D_ParaToCSharp_String: 2048
FB_Simu3D_ReceiveSetpointTCP: 2048
FB_Simu3D_SendJobStringTCP_lokale_Puffer: 2048
FB_Simu3D_SendSetpointTCP: 2048
FB_StringToBuffer: 2048
FUN_ByteSwap_MPLCPower_32BitVars: 2048
FUN_Simu3D_AddSetpointUDP: 2048
FUN_Simu3D_EnterMessage: 2048
FUN_Simu3D_SceneDescrCoding: 2048
FUN_Simu3D_SendSetpointTCP: 2048
MC_ReceiveV2_BigTelegrams_TCP: 2048
MC_SendV2_BigTelegrams_TCP: 2048
PRG_GetRemoteIPViaBroadcast: 2048
PRG_Simu3D_Config_UserCoordSystems: 2048
PRG_Simu3D_DataExchange_CoordSys: 2048
PRG_Simu3D_DataExchange_Kinematics: 2048
NumOfGVLs: 3
GlobalVar_MPLCKinematics_Simulation: 2048
GlobalVar_Simulation_Coordsystems: 2048
Version_MPLCKinematics_Simulation: 2048
END_LIBRARY

LIBRARY
11_System\SysLibStr.lib 27.1.17 13:50:06
(* @LIBRARYSYMFILEINFO := '0' *)
NumOfPOUs: 6
SysStrCmp: 0
SysStrCmpI: 0
SysStrCmpN: 0
SysStrCmpNI: 0
SysStrCpy: 0
SysStrLen: 0
NumOfGVLs: 1
Globale_Variablen: 0
END_LIBRARY

LIBRARY
Internal\MPLCIntern_Kinematics.lib 30.1.17 00:00:00
(* @LIBRARYSYMFILEINFO := '0' *)
NumOfPOUs: 118
FB_Derivation_TaskPriority: 2048
FB_KinAkima: 2048
FB_KinAxisCouplingSystem: 2048
FB_KinAxisDecouplingSystem: 2048
FB_KinAxisIncrToAxisValues: 2048
FB_KinAxisValuesToAxisIncr: 2048
FB_KinBijectionConfigSystem: 2048
FB_KinBijectionDirectSystem: 2048
FB_KinBijectionInverseSystem: 2048
FB_KinCalcCL_2D: 2048
FB_KinCalcCLBlending_Cyclic: 2048
FB_KinCalcCLBlending_Init: 2048
FB_KinCartModuloRangeShift: 2048
FB_KinCircleCenterCorrection_In2D: 2048
FB_KinCircleFrom_Start_End_Center_In2D: 2048
FB_KinCircleFrom_Start_End_Radius_In2D: 2048
FB_KinConfigCheckOnlyParValue: 2048
FB_KinConfigCheckWithoutParValue: 2048
FB_KinControl: 2048
FB_KinControl.A_Config: 2048
FB_KinControl.B_Back: 2048
FB_KinControl.C_Parameter: 2048
FB_KinControl.D_Target: 2048
FB_KinControl.E_Position: 2048
FB_KinControl.F_Motion: 2048
FB_KinControl.G_Continuous: 2048
FB_KinControl.H_Init: 2048
FB_KinControl.I_Check: 2048
FB_KinControl.J_Position: 2048
FB_KinControl.K_Linear: 2048
FB_KinControl.L_Circular: 2048
FB_KinControl.M_Axis: 2048
FB_KinControl.N_Blending: 2048
FB_KinControl.O_Look: 2048
FB_KinControl.P_Execute: 2048
FB_KinControl.Q_Transform: 2048
FB_KinControl_Simu3DDataFilling: 2048
FB_KinConvertFrameToVector: 2048
FB_KinConvertPoseRadToDegr: 2048
FB_KinConvertVectorToFrame: 2048
FB_KinCoordSysMeasurementComputation: 2048
FB_KinDifferentiate3Points_In2D: 2048
FB_KinDirNumeric: 2048
FB_KinDirNumeric.Transform: 2048
FB_KinDirSystem: 2048
FB_KinDirSystem.ACTION_KIN_DIR_TRIPOD_LLL_XYZ_M10: 2048
FB_KinDirSystem.ACTION_KIN_DIR_TRIPOD_RRR_XYZ_M10: 2048
FB_KinFrameInversion: 2048
FB_KinFrameMultiplication: 2048
FB_KinFrameMultiplication_V6FrameV6Notation: 2048
FB_KinFrameMultiplication_Vect6Notation: 2048
FB_KinIntersect2CirclesIn2D: 2048
FB_KinIntersect2LinesIn2D: 2048
FB_KinIntersect_Circle_CircleSection_In2D: 2048
FB_KinInvSystem: 2048
FB_KinInvSystem.ACTION_KIN_INV_QUADROPOD_LLLL_XYZA_M10: 2048
FB_KinInvSystem.ACTION_KIN_INV_TRIPOD_LLL_XYZ_M10: 2048
FB_KinInvSystem.ACTION_KIN_INV_TRIPOD_RRR_XYZ_M10: 2048
FB_KinMbEntry: 2048
FB_KinPositionFromEncoder: 2048
FB_KinPositionTransformation: 2048
FB_KinProjectPointToLine: 2048
FB_KinSgn: 2048
FB_KinShowMsg: 2048
FB_KinShowMsg.ShowEmptyMessage: 2048
FB_KinShowMsg_ConvertToString: 2048
FB_KinTargSync: 2048
FB_KinTargSync.A_CheckForChange: 2048
FB_KinTargSync.B_TargPosActVel: 2048
FB_KinTargSync.C_FastProfiles: 2048
FB_KinTargSync.D0_AdaptedProfiles: 2048
FB_KinTargSync.D1_TriangleProfile: 2048
FB_KinTargSync.D2_TrapezoidProfileMaxVel: 2048
FB_KinTargSync.D3_TrapezoidProfileMaxAccDec: 2048
FB_KinTargSync.E0_AssignSync: 2048
FB_KinTargSync.E1_HarmonizedDecelerationProfile: 2048
FUN_KinAtan2MinusHPIto3HPI: 2048
FUN_KinAtan2MinusPiToPi: 2048
FUN_KinEnable_CpLookAhead: 2048
FUN_KinEnable_CpLookAhead_AxisAccDec: 2048
FUN_KinEnable_CpLookAheadUsingAkima: 2048
FUN_KinEnable_CpNumericVelocityLimitation: 2048
FUN_KinEnableTest_ConfigCartModuloUse: 2048
FUN_KinEnableTest_ConfigGeneralRealJerkInsteadOfJerkTime: 2048
FUN_KinEnableTest_InGeneralModeAXISCP: 2048
FUN_KinEnableTest_InJogCoordSysTCS: 2048
FUN_KinEnableTest_InTargetCoordSysTCS: 2048
FUN_KinLimCPQind: 2048
FUN_KinMappedAxisValue: 2048
FUN_KinSetAxisKinModelOffset: 2048
FUN_KinTimeForLinearProfile: 2048
FUN_KinVect3Add: 2048
FUN_KinVect3CrossProd: 2048
FUN_KinVect3Norm: 2048
FUN_KinVect3ScalarProd: 2048
FUN_KinVect3ScalarVectProd: 2048
FUN_KinVect3SquareNorm: 2048
FUN_KinVect3Sub: 2048
FUN_KinVect3UnitVect: 2048
FUN_KinVect8TransDist: 2048
PRG_KinCalcBlending1Phase: 2048
PRG_KinCalcBlending3Phases: 2048
PRG_KinCalcBlending3Phases.Circ1: 2048
PRG_KinCalcBlending3Phases.Circ3: 2048
PRG_KinCalcBlendingCL: 2048
PRG_KinCalcBlendingMotion: 2048
PRG_KinLocalVelocityLimitation: 2048
PRG_KinLookAhead: 2048
PRG_KinProfGen_PVA_TJP_PVA_aMax_dMax_jMax: 2048
PRG_KinProfGen_PVA_TJP_PVA_Cyclic: 2048
PRG_KinProfGen_PVA_TJP_PVA_Cyclic_v_a_d_j: 2048
PRG_KinProfGen_PVA_TJP_PVA_Cyclic_vMax: 2048
PRG_KinProfGen_PVA_TJP_PVA_Init: 2048
PRG_KinProfGen_PVA_TJP_PVA_Init.A_Dyn: 2048
PRG_KinProfGen_PVA_TJP_PVA_Init.B_Super: 2048
PRG_KinProfGen_PVA_TJP_PVA_Init.C_Check: 2048
PRG_KinProfGen_PVA_TJP_PVA_Init.D_New: 2048
PRG_KinProfGen_PVA_TJP_PVA_Init_ConstV: 2048
NumOfGVLs: 1
GlobalVar_Intern_Kinematics: 2048
END_LIBRARY

LIBRARY
Internal\MPLCIntern_Kinematics_BC.lib 30.1.17 00:00:00
(* @LIBRARYSYMFILEINFO := '0' *)
NumOfPOUs: 9
FB_KinAxisCouplingSystem_BC: 2048
FB_KinAxisDecouplingSystem_BC: 2048
FB_KinBijectionConfigSystem_BC: 2048
FB_KinBijectionDirectSystem_BC: 2048
FB_KinBijectionInverseSystem_BC: 2048
FB_KinConfigCheckOnlyParValue_BC: 2048
FB_KinConfigCheckWithoutParValue_BC: 2048
FB_KinDirSystem_BC: 2048
FB_KinInvSystem_BC: 2048
NumOfGVLs: 0
END_LIBRARY

LIBRARY
Internal\MPLCIntern_Kinematics_Small.lib 30.1.17 00:00:00
(* @LIBRARYSYMFILEINFO := '0' *)
NumOfPOUs: 0
NumOfGVLs: 1
GlobalVar_Intern_Kinematics_Small: 2048
END_LIBRARY
